// 500 High-frequency Dutch Nouns
// Format: { article, nl (singular), plural, en (English), fr (French) }
// Articles: "de" (common gender) or "het" (neuter gender)

const DUTCH_NOUNS = [
  // ── People & Relationships ──────────────────────────────────────────────
  { article: "de",  nl: "man",           plural: "mannen",          en: "man",                fr: "homme" },
  { article: "de",  nl: "vrouw",         plural: "vrouwen",         en: "woman",              fr: "femme" },
  { article: "het", nl: "kind",          plural: "kinderen",        en: "child",              fr: "enfant" },
  { article: "het", nl: "meisje",        plural: "meisjes",         en: "girl",               fr: "fille" },
  { article: "de",  nl: "jongen",        plural: "jongens",         en: "boy",                fr: "garçon" },
  { article: "de",  nl: "vader",         plural: "vaders",          en: "father",             fr: "père" },
  { article: "de",  nl: "moeder",        plural: "moeders",         en: "mother",             fr: "mère" },
  { article: "de",  nl: "broer",         plural: "broers",          en: "brother",            fr: "frère" },
  { article: "de",  nl: "zus",           plural: "zussen",          en: "sister",             fr: "sœur" },
  { article: "de",  nl: "vriend",        plural: "vrienden",        en: "friend (m)",         fr: "ami" },
  { article: "de",  nl: "vriendin",      plural: "vriendinnen",     en: "friend (f)",         fr: "amie" },
  { article: "de",  nl: "familie",       plural: "families",        en: "family",             fr: "famille" },
  { article: "het", nl: "gezin",         plural: "gezinnen",        en: "household/family",   fr: "famille nucléaire" },
  { article: "de",  nl: "ouder",         plural: "ouders",          en: "parent",             fr: "parent" },
  { article: "de",  nl: "opa",           plural: "opa's",           en: "grandfather",        fr: "grand-père" },
  { article: "de",  nl: "oma",           plural: "oma's",           en: "grandmother",        fr: "grand-mère" },
  { article: "de",  nl: "baby",          plural: "baby's",          en: "baby",               fr: "bébé" },
  { article: "de",  nl: "persoon",       plural: "personen",        en: "person",             fr: "personne" },
  { article: "de",  nl: "mens",          plural: "mensen",          en: "person/human",       fr: "être humain" },
  { article: "de",  nl: "buurman",       plural: "buurmannen",      en: "male neighbour",     fr: "voisin" },
  { article: "de",  nl: "buurvrouw",     plural: "buurvrouwen",     en: "female neighbour",   fr: "voisine" },
  { article: "de",  nl: "kennis",        plural: "kennissen",       en: "acquaintance",       fr: "connaissance" },
  { article: "de",  nl: "gast",          plural: "gasten",          en: "guest",              fr: "invité" },
  { article: "de",  nl: "volwassene",    plural: "volwassenen",     en: "adult",              fr: "adulte" },
  { article: "de",  nl: "tiener",        plural: "tieners",         en: "teenager",           fr: "adolescent" },

  // ── Body ────────────────────────────────────────────────────────────────
  { article: "het", nl: "hoofd",         plural: "hoofden",         en: "head",               fr: "tête" },
  { article: "het", nl: "oog",           plural: "ogen",            en: "eye",                fr: "œil" },
  { article: "het", nl: "oor",           plural: "oren",            en: "ear",                fr: "oreille" },
  { article: "de",  nl: "mond",          plural: "monden",          en: "mouth",              fr: "bouche" },
  { article: "de",  nl: "neus",          plural: "neuzen",          en: "nose",               fr: "nez" },
  { article: "de",  nl: "hand",          plural: "handen",          en: "hand",               fr: "main" },
  { article: "de",  nl: "voet",          plural: "voeten",          en: "foot",               fr: "pied" },
  { article: "het", nl: "been",          plural: "benen",           en: "leg",                fr: "jambe" },
  { article: "de",  nl: "arm",           plural: "armen",           en: "arm",                fr: "bras" },
  { article: "de",  nl: "rug",           plural: "ruggen",          en: "back",               fr: "dos" },
  { article: "de",  nl: "buik",          plural: "buiken",          en: "belly/stomach",      fr: "ventre" },
  { article: "het", nl: "hart",          plural: "harten",          en: "heart",              fr: "cœur" },
  { article: "de",  nl: "tand",          plural: "tanden",          en: "tooth",              fr: "dent" },
  { article: "de",  nl: "vinger",        plural: "vingers",         en: "finger",             fr: "doigt" },
  { article: "de",  nl: "wang",          plural: "wangen",          en: "cheek",              fr: "joue" },
  { article: "de",  nl: "nek",           plural: "nekken",          en: "neck",               fr: "cou" },
  { article: "de",  nl: "schouder",      plural: "schouders",       en: "shoulder",           fr: "épaule" },
  { article: "de",  nl: "knie",          plural: "knieën",          en: "knee",               fr: "genou" },
  { article: "de",  nl: "lip",           plural: "lippen",          en: "lip",                fr: "lèvre" },
  { article: "het", nl: "haar",          plural: "haren",           en: "hair",               fr: "cheveu" },
  { article: "de",  nl: "huid",          plural: "huiden",          en: "skin",               fr: "peau" },
  { article: "het", nl: "bloed",         plural: "-",               en: "blood",              fr: "sang" },
  { article: "het", nl: "bot",           plural: "botten",          en: "bone",               fr: "os" },
  { article: "de",  nl: "spier",         plural: "spieren",         en: "muscle",             fr: "muscle" },
  { article: "de",  nl: "long",          plural: "longen",          en: "lung",               fr: "poumon" },
  { article: "de",  nl: "maag",          plural: "magen",           en: "stomach",            fr: "estomac" },
  { article: "het", nl: "gezicht",       plural: "gezichten",       en: "face",               fr: "visage" },
  { article: "de",  nl: "borst",         plural: "borsten",         en: "chest",              fr: "poitrine" },
  { article: "de",  nl: "teen",          plural: "tenen",           en: "toe",                fr: "orteil" },
  { article: "de",  nl: "pols",          plural: "polsen",          en: "wrist",              fr: "poignet" },

  // ── Home & Household ────────────────────────────────────────────────────
  { article: "het", nl: "huis",          plural: "huizen",          en: "house",              fr: "maison" },
  { article: "de",  nl: "kamer",         plural: "kamers",          en: "room",               fr: "pièce" },
  { article: "de",  nl: "deur",          plural: "deuren",          en: "door",               fr: "porte" },
  { article: "het", nl: "raam",          plural: "ramen",           en: "window",             fr: "fenêtre" },
  { article: "de",  nl: "tafel",         plural: "tafels",          en: "table",              fr: "table" },
  { article: "de",  nl: "stoel",         plural: "stoelen",         en: "chair",              fr: "chaise" },
  { article: "het", nl: "bed",           plural: "bedden",          en: "bed",                fr: "lit" },
  { article: "de",  nl: "kast",          plural: "kasten",          en: "cupboard",           fr: "armoire" },
  { article: "de",  nl: "lamp",          plural: "lampen",          en: "lamp",               fr: "lampe" },
  { article: "de",  nl: "vloer",         plural: "vloeren",         en: "floor",              fr: "sol" },
  { article: "de",  nl: "muur",          plural: "muren",           en: "wall",               fr: "mur" },
  { article: "het", nl: "dak",           plural: "daken",           en: "roof",               fr: "toit" },
  { article: "de",  nl: "keuken",        plural: "keukens",         en: "kitchen",            fr: "cuisine" },
  { article: "de",  nl: "badkamer",      plural: "badkamers",       en: "bathroom",           fr: "salle de bain" },
  { article: "de",  nl: "woonkamer",     plural: "woonkamers",      en: "living room",        fr: "salon" },
  { article: "de",  nl: "slaapkamer",    plural: "slaapkamers",     en: "bedroom",            fr: "chambre" },
  { article: "de",  nl: "trap",          plural: "trappen",         en: "stairs",             fr: "escalier" },
  { article: "de",  nl: "gang",          plural: "gangen",          en: "hallway",            fr: "couloir" },
  { article: "de",  nl: "tuin",          plural: "tuinen",          en: "garden",             fr: "jardin" },
  { article: "het", nl: "plafond",       plural: "plafonds",        en: "ceiling",            fr: "plafond" },
  { article: "de",  nl: "bank",          plural: "banken",          en: "sofa",               fr: "canapé" },
  { article: "de",  nl: "koelkast",      plural: "koelkasten",      en: "refrigerator",       fr: "réfrigérateur" },
  { article: "de",  nl: "oven",          plural: "ovens",           en: "oven",               fr: "four" },
  { article: "de",  nl: "douche",        plural: "douches",         en: "shower",             fr: "douche" },
  { article: "het", nl: "bad",           plural: "baden",           en: "bath",               fr: "baignoire" },
  { article: "het", nl: "toilet",        plural: "toiletten",       en: "toilet",             fr: "toilettes" },
  { article: "de",  nl: "spiegel",       plural: "spiegels",        en: "mirror",             fr: "miroir" },
  { article: "het", nl: "gordijn",       plural: "gordijnen",       en: "curtain",            fr: "rideau" },
  { article: "de",  nl: "sleutel",       plural: "sleutels",        en: "key",                fr: "clé" },
  { article: "het", nl: "kussen",        plural: "kussens",         en: "pillow",             fr: "oreiller" },

  // ── Food & Drink ────────────────────────────────────────────────────────
  { article: "het", nl: "brood",         plural: "broden",          en: "bread",              fr: "pain" },
  { article: "de",  nl: "melk",          plural: "-",               en: "milk",               fr: "lait" },
  { article: "de",  nl: "koffie",        plural: "koffies",         en: "coffee",             fr: "café" },
  { article: "de",  nl: "thee",          plural: "theeën",          en: "tea",                fr: "thé" },
  { article: "het", nl: "bier",          plural: "bieren",          en: "beer",               fr: "bière" },
  { article: "de",  nl: "wijn",          plural: "wijnen",          en: "wine",               fr: "vin" },
  { article: "het", nl: "vlees",         plural: "-",               en: "meat",               fr: "viande" },
  { article: "de",  nl: "vis",           plural: "vissen",          en: "fish",               fr: "poisson" },
  { article: "de",  nl: "groente",       plural: "groenten",        en: "vegetable",          fr: "légume" },
  { article: "het", nl: "fruit",         plural: "-",               en: "fruit",              fr: "fruit" },
  { article: "de",  nl: "appel",         plural: "appels",          en: "apple",              fr: "pomme" },
  { article: "de",  nl: "aardappel",     plural: "aardappelen",     en: "potato",             fr: "pomme de terre" },
  { article: "de",  nl: "tomaat",        plural: "tomaten",         en: "tomato",             fr: "tomate" },
  { article: "de",  nl: "ui",            plural: "uien",            en: "onion",              fr: "oignon" },
  { article: "de",  nl: "kaas",          plural: "kazen",           en: "cheese",             fr: "fromage" },
  { article: "het", nl: "ei",            plural: "eieren",          en: "egg",                fr: "œuf" },
  { article: "de",  nl: "suiker",        plural: "-",               en: "sugar",              fr: "sucre" },
  { article: "het", nl: "zout",          plural: "-",               en: "salt",               fr: "sel" },
  { article: "de",  nl: "rijst",         plural: "-",               en: "rice",               fr: "riz" },
  { article: "de",  nl: "soep",          plural: "soepen",          en: "soup",               fr: "soupe" },
  { article: "de",  nl: "saus",          plural: "sauzen",          en: "sauce",              fr: "sauce" },
  { article: "het", nl: "koekje",        plural: "koekjes",         en: "biscuit/cookie",     fr: "biscuit" },
  { article: "de",  nl: "chocolade",     plural: "-",               en: "chocolate",          fr: "chocolat" },
  { article: "het", nl: "water",         plural: "-",               en: "water",              fr: "eau" },
  { article: "het", nl: "sap",           plural: "sappen",          en: "juice",              fr: "jus" },
  { article: "de",  nl: "fles",          plural: "flessen",         en: "bottle",             fr: "bouteille" },
  { article: "het", nl: "glas",          plural: "glazen",          en: "glass",              fr: "verre" },
  { article: "het", nl: "bord",          plural: "borden",          en: "plate",              fr: "assiette" },
  { article: "de",  nl: "vork",          plural: "vorken",          en: "fork",               fr: "fourchette" },
  { article: "het", nl: "mes",           plural: "messen",          en: "knife",              fr: "couteau" },
  { article: "de",  nl: "lepel",         plural: "lepels",          en: "spoon",              fr: "cuillère" },
  { article: "de",  nl: "kom",           plural: "kommen",          en: "bowl",               fr: "bol" },
  { article: "de",  nl: "pan",           plural: "pannen",          en: "pan",                fr: "poêle" },
  { article: "het", nl: "broodje",       plural: "broodjes",        en: "bread roll",         fr: "petit pain" },
  { article: "de",  nl: "maaltijd",      plural: "maaltijden",      en: "meal",               fr: "repas" },

  // ── Nature & Environment ─────────────────────────────────────────────────
  { article: "de",  nl: "boom",          plural: "bomen",           en: "tree",               fr: "arbre" },
  { article: "de",  nl: "bloem",         plural: "bloemen",         en: "flower",             fr: "fleur" },
  { article: "het", nl: "gras",          plural: "grassen",         en: "grass",              fr: "herbe" },
  { article: "het", nl: "vuur",          plural: "vuren",           en: "fire",               fr: "feu" },
  { article: "de",  nl: "lucht",         plural: "luchten",         en: "air/sky",            fr: "air/ciel" },
  { article: "de",  nl: "grond",         plural: "gronden",         en: "ground",             fr: "sol" },
  { article: "de",  nl: "aarde",         plural: "-",               en: "earth/soil",         fr: "terre" },
  { article: "de",  nl: "zon",           plural: "zonnen",          en: "sun",                fr: "soleil" },
  { article: "de",  nl: "maan",          plural: "manen",           en: "moon",               fr: "lune" },
  { article: "de",  nl: "ster",          plural: "sterren",         en: "star",               fr: "étoile" },
  { article: "de",  nl: "zee",           plural: "zeeën",           en: "sea",                fr: "mer" },
  { article: "de",  nl: "rivier",        plural: "rivieren",        en: "river",              fr: "rivière" },
  { article: "de",  nl: "berg",          plural: "bergen",          en: "mountain",           fr: "montagne" },
  { article: "het", nl: "bos",           plural: "bossen",          en: "forest",             fr: "forêt" },
  { article: "het", nl: "veld",          plural: "velden",          en: "field",              fr: "champ" },
  { article: "het", nl: "meer",          plural: "meren",           en: "lake",               fr: "lac" },
  { article: "de",  nl: "regen",         plural: "-",               en: "rain",               fr: "pluie" },
  { article: "de",  nl: "wind",          plural: "winden",          en: "wind",               fr: "vent" },
  { article: "de",  nl: "sneeuw",        plural: "-",               en: "snow",               fr: "neige" },
  { article: "het", nl: "ijs",           plural: "-",               en: "ice",                fr: "glace" },
  { article: "de",  nl: "wolk",          plural: "wolken",          en: "cloud",              fr: "nuage" },
  { article: "de",  nl: "storm",         plural: "stormen",         en: "storm",              fr: "tempête" },
  { article: "het", nl: "onweer",        plural: "-",               en: "thunderstorm",       fr: "orage" },
  { article: "de",  nl: "plant",         plural: "planten",         en: "plant",              fr: "plante" },
  { article: "de",  nl: "steen",         plural: "stenen",          en: "stone",              fr: "pierre" },
  { article: "het", nl: "zand",          plural: "-",               en: "sand",               fr: "sable" },
  { article: "het", nl: "blad",          plural: "bladeren",        en: "leaf",               fr: "feuille" },
  { article: "de",  nl: "tak",           plural: "takken",          en: "branch",             fr: "branche" },
  { article: "de",  nl: "wortel",        plural: "wortels",         en: "root",               fr: "racine" },
  { article: "de",  nl: "paddenstoel",   plural: "paddenstoelen",   en: "mushroom",           fr: "champignon" },

  // ── Animals ──────────────────────────────────────────────────────────────
  { article: "de",  nl: "hond",          plural: "honden",          en: "dog",                fr: "chien" },
  { article: "de",  nl: "kat",           plural: "katten",          en: "cat",                fr: "chat" },
  { article: "de",  nl: "vogel",         plural: "vogels",          en: "bird",               fr: "oiseau" },
  { article: "het", nl: "paard",         plural: "paarden",         en: "horse",              fr: "cheval" },
  { article: "de",  nl: "koe",           plural: "koeien",          en: "cow",                fr: "vache" },
  { article: "het", nl: "varken",        plural: "varkens",         en: "pig",                fr: "cochon" },
  { article: "het", nl: "schaap",        plural: "schapen",         en: "sheep",              fr: "mouton" },
  { article: "de",  nl: "kip",           plural: "kippen",          en: "chicken",            fr: "poulet" },
  { article: "de",  nl: "muis",          plural: "muizen",          en: "mouse",              fr: "souris" },
  { article: "het", nl: "konijn",        plural: "konijnen",        en: "rabbit",             fr: "lapin" },
  { article: "de",  nl: "bij",           plural: "bijen",           en: "bee",                fr: "abeille" },
  { article: "de",  nl: "vlinder",       plural: "vlinders",        en: "butterfly",          fr: "papillon" },
  { article: "de",  nl: "spin",          plural: "spinnen",         en: "spider",             fr: "araignée" },
  { article: "de",  nl: "vlieg",         plural: "vliegen",         en: "fly",                fr: "mouche" },
  { article: "de",  nl: "eend",          plural: "eenden",          en: "duck",               fr: "canard" },
  { article: "de",  nl: "uil",           plural: "uilen",           en: "owl",                fr: "hibou" },
  { article: "de",  nl: "leeuw",         plural: "leeuwen",         en: "lion",               fr: "lion" },
  { article: "de",  nl: "beer",          plural: "beren",           en: "bear",               fr: "ours" },
  { article: "de",  nl: "olifant",       plural: "olifanten",       en: "elephant",           fr: "éléphant" },
  { article: "de",  nl: "aap",           plural: "apen",            en: "monkey",             fr: "singe" },

  // ── Transportation & Infrastructure ──────────────────────────────────────
  { article: "de",  nl: "auto",          plural: "auto's",          en: "car",                fr: "voiture" },
  { article: "de",  nl: "fiets",         plural: "fietsen",         en: "bicycle",            fr: "vélo" },
  { article: "de",  nl: "trein",         plural: "treinen",         en: "train",              fr: "train" },
  { article: "de",  nl: "bus",           plural: "bussen",          en: "bus",                fr: "bus" },
  { article: "de",  nl: "tram",          plural: "trams",           en: "tram",               fr: "tram" },
  { article: "het", nl: "vliegtuig",     plural: "vliegtuigen",     en: "airplane",           fr: "avion" },
  { article: "de",  nl: "boot",          plural: "boten",           en: "boat",               fr: "bateau" },
  { article: "het", nl: "schip",         plural: "schepen",         en: "ship",               fr: "navire" },
  { article: "de",  nl: "weg",           plural: "wegen",           en: "road",               fr: "route" },
  { article: "de",  nl: "straat",        plural: "straten",         en: "street",             fr: "rue" },
  { article: "de",  nl: "brug",          plural: "bruggen",         en: "bridge",             fr: "pont" },
  { article: "het", nl: "station",       plural: "stations",        en: "station",            fr: "gare" },
  { article: "het", nl: "vliegveld",     plural: "vliegvelden",     en: "airport",            fr: "aéroport" },
  { article: "de",  nl: "haven",         plural: "havens",          en: "port/harbour",       fr: "port" },
  { article: "het", nl: "verkeer",       plural: "-",               en: "traffic",            fr: "circulation" },
  { article: "de",  nl: "snelweg",       plural: "snelwegen",       en: "motorway",           fr: "autoroute" },
  { article: "de",  nl: "motor",         plural: "motoren",         en: "motorcycle",         fr: "moto" },
  { article: "de",  nl: "taxi",          plural: "taxi's",          en: "taxi",               fr: "taxi" },
  { article: "de",  nl: "metro",         plural: "metro's",         en: "metro/subway",       fr: "métro" },
  { article: "het", nl: "wiel",          plural: "wielen",          en: "wheel",              fr: "roue" },

  // ── Work & Education ─────────────────────────────────────────────────────
  { article: "het", nl: "werk",          plural: "werken",          en: "work",               fr: "travail" },
  { article: "de",  nl: "baan",          plural: "banen",           en: "job",                fr: "emploi" },
  { article: "de",  nl: "school",        plural: "scholen",         en: "school",             fr: "école" },
  { article: "de",  nl: "universiteit",  plural: "universiteiten",  en: "university",         fr: "université" },
  { article: "de",  nl: "les",           plural: "lessen",          en: "lesson",             fr: "cours" },
  { article: "het", nl: "boek",          plural: "boeken",          en: "book",               fr: "livre" },
  { article: "de",  nl: "pen",           plural: "pennen",          en: "pen",                fr: "stylo" },
  { article: "het", nl: "papier",        plural: "papieren",        en: "paper",              fr: "papier" },
  { article: "de",  nl: "computer",      plural: "computers",       en: "computer",           fr: "ordinateur" },
  { article: "de",  nl: "telefoon",      plural: "telefoons",       en: "telephone",          fr: "téléphone" },
  { article: "het", nl: "kantoor",       plural: "kantoren",        en: "office",             fr: "bureau" },
  { article: "de",  nl: "vergadering",   plural: "vergaderingen",   en: "meeting",            fr: "réunion" },
  { article: "het", nl: "project",       plural: "projecten",       en: "project",            fr: "projet" },
  { article: "de",  nl: "collega",       plural: "collega's",       en: "colleague",          fr: "collègue" },
  { article: "de",  nl: "baas",          plural: "bazen",           en: "boss",               fr: "patron" },
  { article: "het", nl: "loon",          plural: "lonen",           en: "wage/salary",        fr: "salaire" },
  { article: "de",  nl: "vakantie",      plural: "vakanties",       en: "holiday/vacation",   fr: "vacances" },
  { article: "de",  nl: "klas",          plural: "klassen",         en: "class/classroom",    fr: "classe" },
  { article: "de",  nl: "leraar",        plural: "leraren",         en: "teacher",            fr: "professeur" },
  { article: "het", nl: "examen",        plural: "examens",         en: "exam",               fr: "examen" },
  { article: "de",  nl: "opdracht",      plural: "opdrachten",      en: "assignment/task",    fr: "devoir/tâche" },
  { article: "het", nl: "cijfer",        plural: "cijfers",         en: "grade/digit",        fr: "note/chiffre" },
  { article: "de",  nl: "bibliotheek",   plural: "bibliotheken",    en: "library",            fr: "bibliothèque" },
  { article: "de",  nl: "agenda",        plural: "agenda's",        en: "diary/schedule",     fr: "agenda" },
  { article: "het", nl: "diploma",       plural: "diploma's",       en: "diploma",            fr: "diplôme" },

  // ── Technology & Media ───────────────────────────────────────────────────
  { article: "het", nl: "scherm",        plural: "schermen",        en: "screen",             fr: "écran" },
  { article: "het", nl: "internet",      plural: "-",               en: "internet",           fr: "internet" },
  { article: "het", nl: "programma",     plural: "programma's",     en: "program",            fr: "programme" },
  { article: "de",  nl: "website",       plural: "websites",        en: "website",            fr: "site web" },
  { article: "de",  nl: "camera",        plural: "camera's",        en: "camera",             fr: "caméra" },
  { article: "de",  nl: "radio",         plural: "radio's",         en: "radio",              fr: "radio" },
  { article: "de",  nl: "televisie",     plural: "televisies",      en: "television",         fr: "télévision" },
  { article: "de",  nl: "krant",         plural: "kranten",         en: "newspaper",          fr: "journal" },
  { article: "het", nl: "tijdschrift",   plural: "tijdschriften",   en: "magazine",           fr: "magazine" },
  { article: "de",  nl: "film",          plural: "films",           en: "film/movie",         fr: "film" },
  { article: "de",  nl: "muziek",        plural: "-",               en: "music",              fr: "musique" },
  { article: "de",  nl: "foto",          plural: "foto's",          en: "photo",              fr: "photo" },
  { article: "het", nl: "bericht",       plural: "berichten",       en: "message",            fr: "message" },
  { article: "de",  nl: "app",           plural: "apps",            en: "app",                fr: "application" },
  { article: "het", nl: "bestand",       plural: "bestanden",       en: "file",               fr: "fichier" },

  // ── Society & Abstract Concepts ──────────────────────────────────────────
  { article: "het", nl: "land",          plural: "landen",          en: "country",            fr: "pays" },
  { article: "de",  nl: "stad",          plural: "steden",          en: "city",               fr: "ville" },
  { article: "het", nl: "dorp",          plural: "dorpen",          en: "village",            fr: "village" },
  { article: "de",  nl: "wereld",        plural: "werelden",        en: "world",              fr: "monde" },
  { article: "het", nl: "leven",         plural: "levens",          en: "life",               fr: "vie" },
  { article: "de",  nl: "dood",          plural: "-",               en: "death",              fr: "mort" },
  { article: "de",  nl: "liefde",        plural: "liefdes",         en: "love",               fr: "amour" },
  { article: "het", nl: "geluk",         plural: "-",               en: "happiness/luck",     fr: "bonheur/chance" },
  { article: "het", nl: "geld",          plural: "-",               en: "money",              fr: "argent" },
  { article: "de",  nl: "macht",         plural: "machten",         en: "power",              fr: "pouvoir" },
  { article: "de",  nl: "wet",           plural: "wetten",          en: "law",                fr: "loi" },
  { article: "het", nl: "recht",         plural: "rechten",         en: "right/law",          fr: "droit" },
  { article: "de",  nl: "vrede",         plural: "-",               en: "peace",              fr: "paix" },
  { article: "de",  nl: "oorlog",        plural: "oorlogen",        en: "war",                fr: "guerre" },
  { article: "de",  nl: "regering",      plural: "regeringen",      en: "government",         fr: "gouvernement" },
  { article: "de",  nl: "politiek",      plural: "-",               en: "politics",           fr: "politique" },
  { article: "de",  nl: "cultuur",       plural: "culturen",        en: "culture",            fr: "culture" },
  { article: "de",  nl: "taal",          plural: "talen",           en: "language",           fr: "langue" },
  { article: "de",  nl: "geschiedenis",  plural: "geschiedenissen", en: "history",            fr: "histoire" },
  { article: "de",  nl: "kunst",         plural: "kunsten",         en: "art",                fr: "art" },
  { article: "de",  nl: "sport",         plural: "sporten",         en: "sport",              fr: "sport" },
  { article: "het", nl: "spel",          plural: "spelen",          en: "game/play",          fr: "jeu" },
  { article: "de",  nl: "religie",       plural: "religies",        en: "religion",           fr: "religion" },
  { article: "de",  nl: "kerk",          plural: "kerken",          en: "church",             fr: "église" },
  { article: "de",  nl: "maatschappij",  plural: "maatschappijen",  en: "society",            fr: "société" },
  { article: "het", nl: "volk",          plural: "volkeren",        en: "people/nation",      fr: "peuple" },
  { article: "de",  nl: "economie",      plural: "economieën",      en: "economy",            fr: "économie" },
  { article: "de",  nl: "wetenschap",    plural: "wetenschappen",   en: "science",            fr: "science" },
  { article: "de",  nl: "technologie",   plural: "technologieën",   en: "technology",         fr: "technologie" },
  { article: "de",  nl: "traditie",      plural: "tradities",       en: "tradition",          fr: "tradition" },
  { article: "de",  nl: "vrijheid",      plural: "vrijheden",       en: "freedom",            fr: "liberté" },
  { article: "de",  nl: "democratie",    plural: "democratieën",    en: "democracy",          fr: "démocratie" },
  { article: "de",  nl: "partij",        plural: "partijen",        en: "party",              fr: "parti" },

  // ── Health & Medicine ─────────────────────────────────────────────────────
  { article: "de",  nl: "gezondheid",    plural: "-",               en: "health",             fr: "santé" },
  { article: "de",  nl: "dokter",        plural: "dokters",         en: "doctor",             fr: "médecin" },
  { article: "het", nl: "ziekenhuis",    plural: "ziekenhuizen",    en: "hospital",           fr: "hôpital" },
  { article: "de",  nl: "medicijn",      plural: "medicijnen",      en: "medicine",           fr: "médicament" },
  { article: "de",  nl: "ziekte",        plural: "ziekten",         en: "illness",            fr: "maladie" },
  { article: "de",  nl: "pijn",          plural: "pijnen",          en: "pain",               fr: "douleur" },
  { article: "de",  nl: "koorts",        plural: "-",               en: "fever",              fr: "fièvre" },
  { article: "de",  nl: "operatie",      plural: "operaties",       en: "operation",          fr: "opération" },
  { article: "de",  nl: "behandeling",   plural: "behandelingen",   en: "treatment",          fr: "traitement" },
  { article: "de",  nl: "wond",          plural: "wonden",          en: "wound",              fr: "blessure" },
  { article: "de",  nl: "apotheek",      plural: "apotheken",       en: "pharmacy",           fr: "pharmacie" },
  { article: "het", nl: "recept",        plural: "recepten",        en: "prescription",       fr: "ordonnance" },
  { article: "de",  nl: "allergie",      plural: "allergieën",      en: "allergy",            fr: "allergie" },
  { article: "het", nl: "vaccin",        plural: "vaccins",         en: "vaccine",            fr: "vaccin" },
  { article: "de",  nl: "ambulance",     plural: "ambulances",      en: "ambulance",          fr: "ambulance" },

  // ── Clothing & Fashion ────────────────────────────────────────────────────
  { article: "de",  nl: "kleding",       plural: "-",               en: "clothing",           fr: "vêtements" },
  { article: "het", nl: "shirt",         plural: "shirts",          en: "shirt",              fr: "chemise" },
  { article: "de",  nl: "broek",         plural: "broeken",         en: "trousers",           fr: "pantalon" },
  { article: "de",  nl: "jurk",          plural: "jurken",          en: "dress",              fr: "robe" },
  { article: "de",  nl: "jas",           plural: "jassen",          en: "coat/jacket",        fr: "manteau" },
  { article: "de",  nl: "schoen",        plural: "schoenen",        en: "shoe",               fr: "chaussure" },
  { article: "de",  nl: "sok",           plural: "sokken",          en: "sock",               fr: "chaussette" },
  { article: "de",  nl: "trui",          plural: "truien",          en: "sweater",            fr: "pull" },
  { article: "de",  nl: "rok",           plural: "rokken",          en: "skirt",              fr: "jupe" },
  { article: "de",  nl: "muts",          plural: "mutsen",          en: "hat/beanie",         fr: "bonnet" },
  { article: "de",  nl: "sjaal",         plural: "sjaals",          en: "scarf",              fr: "écharpe" },
  { article: "de",  nl: "handschoen",    plural: "handschoenen",    en: "glove",              fr: "gant" },
  { article: "de",  nl: "riem",          plural: "riemen",          en: "belt",               fr: "ceinture" },
  { article: "de",  nl: "tas",           plural: "tassen",          en: "bag",                fr: "sac" },
  { article: "de",  nl: "rugzak",        plural: "rugzakken",       en: "backpack",           fr: "sac à dos" },

  // ── Time ──────────────────────────────────────────────────────────────────
  { article: "de",  nl: "tijd",          plural: "tijden",          en: "time",               fr: "temps" },
  { article: "de",  nl: "dag",           plural: "dagen",           en: "day",                fr: "jour" },
  { article: "de",  nl: "nacht",         plural: "nachten",         en: "night",              fr: "nuit" },
  { article: "de",  nl: "ochtend",       plural: "ochtenden",       en: "morning",            fr: "matin" },
  { article: "de",  nl: "middag",        plural: "middagen",        en: "afternoon",          fr: "après-midi" },
  { article: "de",  nl: "avond",         plural: "avonden",         en: "evening",            fr: "soir" },
  { article: "de",  nl: "week",          plural: "weken",           en: "week",               fr: "semaine" },
  { article: "de",  nl: "maand",         plural: "maanden",         en: "month",              fr: "mois" },
  { article: "het", nl: "jaar",          plural: "jaren",           en: "year",               fr: "an/année" },
  { article: "het", nl: "uur",           plural: "uren",            en: "hour",               fr: "heure" },
  { article: "de",  nl: "minuut",        plural: "minuten",         en: "minute",             fr: "minute" },
  { article: "de",  nl: "seconde",       plural: "seconden",        en: "second",             fr: "seconde" },
  { article: "het", nl: "moment",        plural: "momenten",        en: "moment",             fr: "moment" },
  { article: "de",  nl: "toekomst",      plural: "-",               en: "future",             fr: "avenir" },
  { article: "het", nl: "verleden",      plural: "-",               en: "past",               fr: "passé" },
  { article: "het", nl: "seizoen",       plural: "seizoenen",       en: "season",             fr: "saison" },
  { article: "de",  nl: "lente",         plural: "lentes",          en: "spring",             fr: "printemps" },
  { article: "de",  nl: "zomer",         plural: "zomers",          en: "summer",             fr: "été" },
  { article: "de",  nl: "herfst",        plural: "herfsten",        en: "autumn",             fr: "automne" },
  { article: "de",  nl: "winter",        plural: "winters",         en: "winter",             fr: "hiver" },
  { article: "de",  nl: "datum",         plural: "data",            en: "date",               fr: "date" },

  // ── Places ────────────────────────────────────────────────────────────────
  { article: "de",  nl: "markt",         plural: "markten",         en: "market",             fr: "marché" },
  { article: "het", nl: "restaurant",    plural: "restaurants",     en: "restaurant",         fr: "restaurant" },
  { article: "het", nl: "café",          plural: "cafés",           en: "café",               fr: "café" },
  { article: "de",  nl: "winkel",        plural: "winkels",         en: "shop/store",         fr: "magasin" },
  { article: "het", nl: "hotel",         plural: "hotels",          en: "hotel",              fr: "hôtel" },
  { article: "het", nl: "museum",        plural: "musea",           en: "museum",             fr: "musée" },
  { article: "het", nl: "theater",       plural: "theaters",        en: "theatre",            fr: "théâtre" },
  { article: "het", nl: "park",          plural: "parken",          en: "park",               fr: "parc" },
  { article: "het", nl: "strand",        plural: "stranden",        en: "beach",              fr: "plage" },
  { article: "het", nl: "zwembad",       plural: "zwembaden",       en: "swimming pool",      fr: "piscine" },
  { article: "de",  nl: "supermarkt",    plural: "supermarkten",    en: "supermarket",        fr: "supermarché" },
  { article: "de",  nl: "rechtbank",     plural: "rechtbanken",     en: "courthouse",         fr: "tribunal" },
  { article: "het", nl: "politiebureau", plural: "politiebureaus",  en: "police station",     fr: "commissariat" },
  { article: "de",  nl: "gevangenis",    plural: "gevangenissen",   en: "prison",             fr: "prison" },
  { article: "de",  nl: "fabriek",       plural: "fabrieken",       en: "factory",            fr: "usine" },
  { article: "de",  nl: "boerderij",     plural: "boerderijen",     en: "farm",               fr: "ferme" },
  { article: "de",  nl: "wijk",          plural: "wijken",          en: "neighbourhood",      fr: "quartier" },
  { article: "de",  nl: "buurt",         plural: "buurten",         en: "neighbourhood",      fr: "voisinage" },
  { article: "het", nl: "centrum",       plural: "centra",          en: "centre",             fr: "centre" },
  { article: "de",  nl: "omgeving",      plural: "omgevingen",      en: "surroundings",       fr: "environs" },

  // ── Arts & Culture ────────────────────────────────────────────────────────
  { article: "het", nl: "schilderij",    plural: "schilderijen",    en: "painting",           fr: "tableau" },
  { article: "het", nl: "standbeeld",    plural: "standbeelden",    en: "statue",             fr: "statue" },
  { article: "de",  nl: "tekening",      plural: "tekeningen",      en: "drawing",            fr: "dessin" },
  { article: "het", nl: "lied",          plural: "liederen",        en: "song",               fr: "chanson" },
  { article: "het", nl: "gedicht",       plural: "gedichten",       en: "poem",               fr: "poème" },
  { article: "het", nl: "verhaal",       plural: "verhalen",        en: "story",              fr: "histoire" },
  { article: "de",  nl: "roman",         plural: "romans",          en: "novel",              fr: "roman" },
  { article: "de",  nl: "dans",          plural: "dansen",          en: "dance",              fr: "danse" },
  { article: "het", nl: "concert",       plural: "concerten",       en: "concert",            fr: "concert" },
  { article: "het", nl: "festival",      plural: "festivals",       en: "festival",           fr: "festival" },
  { article: "het", nl: "kunstwerk",     plural: "kunstwerken",     en: "artwork",            fr: "œuvre d'art" },
  { article: "de",  nl: "tentoonstelling", plural: "tentoonstellingen", en: "exhibition",     fr: "exposition" },

  // ── Sports ────────────────────────────────────────────────────────────────
  { article: "de",  nl: "voetbal",       plural: "voetballen",      en: "football/soccer",    fr: "football" },
  { article: "de",  nl: "wedstrijd",     plural: "wedstrijden",     en: "match/competition",  fr: "match" },
  { article: "het", nl: "team",          plural: "teams",           en: "team",               fr: "équipe" },
  { article: "de",  nl: "speler",        plural: "spelers",         en: "player",             fr: "joueur" },
  { article: "het", nl: "stadion",       plural: "stadions",        en: "stadium",            fr: "stade" },
  { article: "de",  nl: "trofee",        plural: "trofeeën",        en: "trophy",             fr: "trophée" },
  { article: "de",  nl: "training",      plural: "trainingen",      en: "training",           fr: "entraînement" },

  // ── Finance & Business ────────────────────────────────────────────────────
  { article: "de",  nl: "prijs",         plural: "prijzen",         en: "price",              fr: "prix" },
  { article: "het", nl: "bedrag",        plural: "bedragen",        en: "amount",             fr: "montant" },
  { article: "de",  nl: "rekening",      plural: "rekeningen",      en: "bill/account",       fr: "facture/compte" },
  { article: "het", nl: "inkomen",       plural: "inkomens",        en: "income",             fr: "revenu" },
  { article: "de",  nl: "belasting",     plural: "belastingen",     en: "tax",                fr: "impôt" },
  { article: "de",  nl: "winst",         plural: "winsten",         en: "profit",             fr: "bénéfice" },
  { article: "het", nl: "verlies",       plural: "verliezen",       en: "loss",               fr: "perte" },
  { article: "het", nl: "bedrijf",       plural: "bedrijven",       en: "company",            fr: "entreprise" },
  { article: "het", nl: "contract",      plural: "contracten",      en: "contract",           fr: "contrat" },
  { article: "het", nl: "budget",        plural: "budgetten",       en: "budget",             fr: "budget" },
  { article: "de",  nl: "klant",         plural: "klanten",         en: "customer",           fr: "client" },
  { article: "het", nl: "product",       plural: "producten",       en: "product",            fr: "produit" },
  { article: "de",  nl: "investering",   plural: "investeringen",   en: "investment",         fr: "investissement" },

  // ── Communication ─────────────────────────────────────────────────────────
  { article: "het", nl: "gesprek",       plural: "gesprekken",      en: "conversation",       fr: "conversation" },
  { article: "de",  nl: "vraag",         plural: "vragen",          en: "question",           fr: "question" },
  { article: "het", nl: "antwoord",      plural: "antwoorden",      en: "answer",             fr: "réponse" },
  { article: "het", nl: "nieuws",        plural: "-",               en: "news",               fr: "nouvelles" },
  { article: "de",  nl: "mening",        plural: "meningen",        en: "opinion",            fr: "opinion" },
  { article: "de",  nl: "discussie",     plural: "discussies",      en: "discussion",         fr: "discussion" },
  { article: "het", nl: "debat",         plural: "debatten",        en: "debate",             fr: "débat" },
  { article: "de",  nl: "toespraak",     plural: "toespraken",      en: "speech",             fr: "discours" },
  { article: "de",  nl: "brief",         plural: "brieven",         en: "letter",             fr: "lettre" },
  { article: "het", nl: "woord",         plural: "woorden",         en: "word",               fr: "mot" },
  { article: "de",  nl: "zin",           plural: "zinnen",          en: "sentence",           fr: "phrase" },
  { article: "de",  nl: "stem",          plural: "stemmen",         en: "voice/vote",         fr: "voix/vote" },

  // ── Emotions & Psychology ─────────────────────────────────────────────────
  { article: "het", nl: "gevoel",        plural: "gevoelens",       en: "feeling",            fr: "sentiment" },
  { article: "de",  nl: "emotie",        plural: "emoties",         en: "emotion",            fr: "émotion" },
  { article: "de",  nl: "angst",         plural: "angsten",         en: "fear/anxiety",       fr: "peur/angoisse" },
  { article: "de",  nl: "vreugde",       plural: "-",               en: "joy",                fr: "joie" },
  { article: "de",  nl: "boosheid",      plural: "-",               en: "anger",              fr: "colère" },
  { article: "de",  nl: "hoop",          plural: "hopen",           en: "hope",               fr: "espoir" },
  { article: "de",  nl: "teleurstelling",plural: "teleurstellingen", en: "disappointment",    fr: "déception" },
  { article: "het", nl: "vertrouwen",    plural: "-",               en: "trust/confidence",   fr: "confiance" },
  { article: "de",  nl: "trots",         plural: "-",               en: "pride",              fr: "fierté" },
  { article: "de",  nl: "schaamte",      plural: "-",               en: "shame",              fr: "honte" },
  { article: "de",  nl: "eenzaamheid",   plural: "-",               en: "loneliness",         fr: "solitude" },
  { article: "de",  nl: "stress",        plural: "-",               en: "stress",             fr: "stress" },

  // ── Abstract & General ────────────────────────────────────────────────────
  { article: "het", nl: "probleem",      plural: "problemen",       en: "problem",            fr: "problème" },
  { article: "de",  nl: "oplossing",     plural: "oplossingen",     en: "solution",           fr: "solution" },
  { article: "de",  nl: "kans",          plural: "kansen",          en: "chance/opportunity", fr: "chance/opportunité" },
  { article: "het", nl: "risico",        plural: "risico's",        en: "risk",               fr: "risque" },
  { article: "de",  nl: "keuze",         plural: "keuzen",          en: "choice",             fr: "choix" },
  { article: "het", nl: "doel",          plural: "doelen",          en: "goal/aim",           fr: "but/objectif" },
  { article: "het", nl: "resultaat",     plural: "resultaten",      en: "result",             fr: "résultat" },
  { article: "de",  nl: "reden",         plural: "redenen",         en: "reason",             fr: "raison" },
  { article: "het", nl: "belang",        plural: "belangen",        en: "importance/interest",fr: "importance/intérêt" },
  { article: "de",  nl: "invloed",       plural: "invloeden",       en: "influence",          fr: "influence" },
  { article: "het", nl: "verschil",      plural: "verschillen",     en: "difference",         fr: "différence" },
  { article: "het", nl: "voorbeeld",     plural: "voorbeelden",     en: "example",            fr: "exemple" },
  { article: "de",  nl: "mogelijkheid",  plural: "mogelijkheden",   en: "possibility",        fr: "possibilité" },
  { article: "het", nl: "voordeel",      plural: "voordelen",       en: "advantage",          fr: "avantage" },
  { article: "het", nl: "nadeel",        plural: "nadelen",         en: "disadvantage",       fr: "inconvénient" },
  { article: "de",  nl: "verandering",   plural: "veranderingen",   en: "change",             fr: "changement" },
  { article: "de",  nl: "ontwikkeling",  plural: "ontwikkelingen",  en: "development",        fr: "développement" },
  { article: "het", nl: "succes",        plural: "successen",       en: "success",            fr: "succès" },
  { article: "de",  nl: "mislukking",    plural: "mislukkingen",    en: "failure",            fr: "échec" },
  { article: "het", nl: "begin",         plural: "beginnen",        en: "beginning",          fr: "début" },
  { article: "het", nl: "einde",         plural: "einden",          en: "end",                fr: "fin" },
  { article: "de",  nl: "groep",         plural: "groepen",         en: "group",              fr: "groupe" },
  { article: "het", nl: "deel",          plural: "delen",           en: "part",               fr: "partie" },
  { article: "het", nl: "geheel",        plural: "gehelen",         en: "whole",              fr: "ensemble" },
  { article: "de",  nl: "soort",         plural: "soorten",         en: "type/kind",          fr: "type/sorte" },
  { article: "de",  nl: "manier",        plural: "manieren",        en: "way/manner",         fr: "façon/manière" },
  { article: "het", nl: "systeem",       plural: "systemen",        en: "system",             fr: "système" },
  { article: "het", nl: "niveau",        plural: "niveaus",         en: "level",              fr: "niveau" },
  { article: "de",  nl: "stap",          plural: "stappen",         en: "step",               fr: "étape/pas" },
  { article: "het", nl: "plan",          plural: "plannen",         en: "plan",               fr: "plan" },

  // ── Quantity & Measurement ─────────────────────────────────────────────────
  { article: "het", nl: "aantal",        plural: "aantallen",       en: "number/quantity",    fr: "nombre/quantité" },
  { article: "de",  nl: "hoeveelheid",   plural: "hoeveelheden",    en: "amount/quantity",    fr: "quantité" },
  { article: "het", nl: "gewicht",       plural: "gewichten",       en: "weight",             fr: "poids" },
  { article: "de",  nl: "lengte",        plural: "lengten",         en: "length/height",      fr: "longueur/taille" },
  { article: "de",  nl: "breedte",       plural: "breedten",        en: "width",              fr: "largeur" },
  { article: "de",  nl: "hoogte",        plural: "hoogten",         en: "height",             fr: "hauteur" },
  { article: "de",  nl: "diepte",        plural: "diepten",         en: "depth",              fr: "profondeur" },
  { article: "de",  nl: "snelheid",      plural: "snelheden",       en: "speed",              fr: "vitesse" },
  { article: "de",  nl: "temperatuur",   plural: "temperaturen",    en: "temperature",        fr: "température" },
  { article: "de",  nl: "afstand",       plural: "afstanden",       en: "distance",           fr: "distance" },

  // ── School supplies & office ──────────────────────────────────────────────
  { article: "het", nl: "schrift",       plural: "schriften",       en: "exercise book",      fr: "cahier" },
  { article: "het", nl: "potlood",       plural: "potloden",        en: "pencil",             fr: "crayon" },
  { article: "de",  nl: "gum",           plural: "gummen",          en: "eraser",             fr: "gomme" },
  { article: "de",  nl: "liniaal",       plural: "linealen",        en: "ruler",              fr: "règle" },
  { article: "de",  nl: "map",           plural: "mappen",          en: "folder",             fr: "classeur" },
  { article: "het", nl: "schaar",        plural: "scharen",         en: "scissors",           fr: "ciseaux" },
  { article: "het", nl: "plakband",      plural: "plakbanden",      en: "sticky tape",        fr: "ruban adhésif" },
  { article: "de",  nl: "printer",       plural: "printers",        en: "printer",            fr: "imprimante" },

  // ── Numbers & money ───────────────────────────────────────────────────────
  { article: "het", nl: "getal",         plural: "getallen",        en: "number",             fr: "nombre" },
  { article: "de",  nl: "munt",          plural: "munten",          en: "coin",               fr: "pièce" },
  { article: "het", nl: "biljet",        plural: "biljetten",       en: "banknote",           fr: "billet" },
  { article: "de",  nl: "portemonnee",   plural: "portemonnees",    en: "wallet/purse",       fr: "portefeuille" },
  { article: "de",  nl: "creditcard",    plural: "creditcards",     en: "credit card",        fr: "carte de crédit" },

  // ── Weather & climate ─────────────────────────────────────────────────────
  { article: "het", nl: "weer",          plural: "-",               en: "weather",            fr: "temps/météo" },
  { article: "de",  nl: "neerslag",       plural: "-",               en: "precipitation",      fr: "précipitations" },
  { article: "de",  nl: "bliksem",       plural: "-",               en: "lightning",          fr: "éclair" },
  { article: "de",  nl: "donder",        plural: "-",               en: "thunder",            fr: "tonnerre" },
  { article: "de",  nl: "mist",          plural: "misten",          en: "fog",                fr: "brouillard" },

  // ── Materials & objects ───────────────────────────────────────────────────
  { article: "het", nl: "hout",          plural: "houten",          en: "wood",               fr: "bois" },
  { article: "het", nl: "metaal",        plural: "metalen",         en: "metal",              fr: "métal" },
  { article: "het", nl: "plastic",       plural: "plastics",        en: "plastic",            fr: "plastique" },
  { article: "het", nl: "ijzer",          plural: "ijzers",          en: "iron (metal)",       fr: "fer" },
  { article: "het", nl: "leer",          plural: "-",               en: "leather",            fr: "cuir" },
  { article: "de",  nl: "stof",          plural: "stoffen",         en: "fabric/dust",        fr: "tissu/poussière" },
  { article: "het", nl: "karton",        plural: "kartons",          en: "cardboard",          fr: "carton" },
  { article: "het", nl: "rubber",        plural: "-",               en: "rubber",             fr: "caoutchouc" },

  // ── Tools & devices ───────────────────────────────────────────────────────
  { article: "de",  nl: "hamer",         plural: "hamers",          en: "hammer",             fr: "marteau" },
  { article: "de",  nl: "schroef",       plural: "schroeven",       en: "screw",              fr: "vis" },
  { article: "de",  nl: "spijker",       plural: "spijkers",        en: "nail",               fr: "clou" },
  { article: "het", nl: "gereedschap",   plural: "gereedschappen",  en: "tool",               fr: "outil" },
  { article: "het", nl: "apparaat",      plural: "apparaten",       en: "device/appliance",   fr: "appareil" },
  { article: "de",  nl: "machine",       plural: "machines",        en: "machine",            fr: "machine" },

  // ── Science & nature ─────────────────────────────────────────────────────
  { article: "de",  nl: "energie",       plural: "energieën",       en: "energy",             fr: "énergie" },
  { article: "de",  nl: "kracht",        plural: "krachten",        en: "force/strength",     fr: "force" },
  { article: "het", nl: "licht",         plural: "lichten",         en: "light",              fr: "lumière" },
  { article: "het", nl: "geluid",        plural: "geluiden",        en: "sound",              fr: "son" },
  { article: "de",  nl: "warmte",        plural: "-",               en: "heat/warmth",        fr: "chaleur" },
  { article: "de",  nl: "molecule",      plural: "moleculen",       en: "molecule",           fr: "molécule" },
  { article: "het", nl: "experiment",    plural: "experimenten",    en: "experiment",         fr: "expérience" },
  { article: "de",  nl: "theorie",       plural: "theorieën",       en: "theory",             fr: "théorie" },

  // ── Travel & leisure ─────────────────────────────────────────────────────
  { article: "de",  nl: "reis",          plural: "reizen",          en: "journey/trip",       fr: "voyage" },
  { article: "het", nl: "paspoort",      plural: "paspoorten",      en: "passport",           fr: "passeport" },
  { article: "de",  nl: "koffer",        plural: "koffers",         en: "suitcase",           fr: "valise" },
  { article: "het", nl: "ticket",        plural: "tickets",         en: "ticket",             fr: "billet" },
  { article: "het", nl: "kaartje",       plural: "kaartjes",        en: "ticket/card",        fr: "billet/carte" },
  { article: "de",  nl: "kaart",         plural: "kaarten",         en: "map/card",           fr: "carte" },
  { article: "het", nl: "toerisme",      plural: "-",               en: "tourism",            fr: "tourisme" },
  { article: "de",  nl: "attractie",     plural: "attracties",      en: "attraction",         fr: "attraction" },

  // ── Colours (as nouns) ────────────────────────────────────────────────────
  { article: "de",  nl: "kleur",         plural: "kleuren",         en: "colour",             fr: "couleur" },
  { article: "het", nl: "rood",          plural: "-",               en: "red",                fr: "rouge" },
  { article: "het", nl: "blauw",         plural: "-",               en: "blue",               fr: "bleu" },
  { article: "het", nl: "groen",         plural: "-",               en: "green",              fr: "vert" },
  { article: "het", nl: "geel",          plural: "-",               en: "yellow",             fr: "jaune" },
  { article: "het", nl: "zwart",         plural: "-",               en: "black",              fr: "noir" },
  { article: "het", nl: "wit",           plural: "-",               en: "white",              fr: "blanc" },

  // ── Additional high-frequency ─────────────────────────────────────────────
  { article: "het", nl: "adres",         plural: "adressen",        en: "address",            fr: "adresse" },
  { article: "het", nl: "nummer",        plural: "nummers",         en: "number",             fr: "numéro" },
  { article: "de",  nl: "naam",          plural: "namen",           en: "name",               fr: "nom" },
  { article: "het", nl: "onderwerp",     plural: "onderwerpen",     en: "subject/topic",      fr: "sujet" },
  { article: "de",  nl: "informatie",    plural: "-",               en: "information",        fr: "information" },
  { article: "het", nl: "idee",          plural: "ideeën",          en: "idea",               fr: "idée" },
  { article: "het", nl: "model",         plural: "modellen",        en: "model",              fr: "modèle" },
  { article: "de",  nl: "stijl",         plural: "stijlen",         en: "style",              fr: "style" },
  { article: "het", nl: "effect",        plural: "effecten",        en: "effect",             fr: "effet" },
  { article: "het", nl: "gevaar",        plural: "gevaren",         en: "danger",             fr: "danger" },
  { article: "de",  nl: "veiligheid",    plural: "-",               en: "safety/security",    fr: "sécurité" },
  { article: "de",  nl: "kwaliteit",     plural: "kwaliteiten",     en: "quality",            fr: "qualité" },
  { article: "de",  nl: "omvang",        plural: "omvangen",        en: "size/extent",        fr: "ampleur/taille" },
  { article: "het", nl: "verslag",       plural: "verslagen",       en: "report",             fr: "rapport" },
  { article: "de",  nl: "sfeer",         plural: "sferen",          en: "atmosphere/mood",    fr: "ambiance" },
];

// Quick stats
console.log(`Total nouns: ${DUTCH_NOUNS.length}`);
console.log(`"de" nouns: ${DUTCH_NOUNS.filter(n => n.article === "de").length}`);
console.log(`"het" nouns: ${DUTCH_NOUNS.filter(n => n.article === "het").length}`);

// Export for use in other scripts
if (typeof module !== "undefined") module.exports = { DUTCH_NOUNS };
