# French gloss + example sentences (parallel to EN) for each Dutch infinitive.
# Tuple: (french_infinitive_gloss, sentence_singular_fr, sentence_plural_fr)
FRENCH_BY_VERB = {
    "zijn": ("être", "J'étais fatigué hier.", "Nous étions à l'école ensemble."),
    "hebben": ("avoir", "Je n'avais pas le temps.", "Elles avaient beaucoup de questions."),
    "worden": ("devenir", "Il est devenu médecin.", "Nous sommes devenus de bons amis."),
    "gaan": ("aller", "Je suis allé à pied.", "Elles sont allées en bus."),
    "komen": ("venir", "Il venait de Berlin.", "Nous sommes arrivés trop tard."),
    "blijven": ("rester", "Je suis resté chez moi.", "Vous êtes restés une semaine de plus."),
    "zitten": ("être assis", "J'étais près de la fenêtre.", "Elles étaient dans la salle."),
    "staan": ("être debout", "Il faisait la queue.", "Nous étions sur le quai."),
    "liggen": ("être couché", "Le livre était sur la table.", "Les clés étaient dans le tiroir."),
    "lopen": ("marcher", "Je suis rentré à pied.", "Elles ont traversé le parc."),
    "doen": ("faire", "J'ai fait de mon mieux.", "Nous l'avons fait ensemble."),
    "maken": ("fabriquer / faire", "Elle a fait de la soupe.", "Elles ont fait beaucoup de bruit."),
    "zeggen": ("dire", "Il a dit la vérité.", "Nous l'avons répété."),
    "geven": ("donner", "Je lui ai offert un cadeau.", "Nous avons donné à une association."),
    "nemen": ("prendre", "Tu as pris la mauvaise sortie.", "Nous avons pris un taxi."),
    "zien": ("voir", "J'ai vu un arc-en-ciel.", "Elles avaient déjà vu le film."),
    "weten": ("savoir", "Il connaissait la réponse.", "Nous ne savions pas où aller."),
    "vinden": ("trouver", "J'ai retrouvé ma clé.", "Elles n'ont trouvé aucune place."),
    "denken": ("penser", "Je pensais à toi.", "Nous cherchions une solution."),
    "laten": ("laisser", "Il a laissé la porte ouverte.", "Nous avons laissé les enfants jouer."),
    "willen": ("vouloir", "Je voulais aider.", "Nous voulions aller à la plage."),
    "moeten": ("devoir", "Je devais faire des heures sup.", "Nous devions nous dépêcher."),
    "kunnen": ("pouvoir", "Je ne pouvais pas venir.", "Nous ne pouvions pas nous entendre."),
    "mogen": ("avoir le droit de", "Je n'avais pas le droit de fumer.", "Nous avons pu dormir sur place."),
    "brengen": ("apporter", "J'ai apporté du café.", "Elles ont apporté des fleurs."),
    "halen": ("aller chercher", "Il est allé chercher les enfants.", "Nous avons pris du pain chez le boulanger."),
    "houden": ("tenir", "Je lui tenais la main.", "Elles ont prononcé un discours."),
    "kopen": ("acheter", "Elle a acheté un vélo.", "Elles ont acheté une maison."),
    "verkopen": ("vendre", "Il a vendu sa voiture.", "Elles ont vendu de vieux livres."),
    "betalen": ("payer", "J'ai payé en espèces.", "Nous avons payé l'addition."),
    "werken": ("travailler", "Je travaillais à l'hôpital.", "Nous étions dans la même équipe."),
    "spelen": ("jouer", "Il jouait de la guitare.", "Elles ont joué un match."),
    "leren": ("apprendre", "J'apprenais le néerlandais.", "Nous nous sommes connus à l'école."),
    "studieren": ("étudier", "Tu as étudié la médecine.", "Elles ont étudié à Leyde."),
    "wonen": ("habiter", "Je vivais chez mes parents.", "Nous avons vécu des années à Utrecht."),
    "lezen": ("lire", "Je lisais un livre chaque soir.", "Nous avons lu tout l'article."),
    "schrijven": ("écrire", "Il a écrit une lettre.", "Elles ont écrit leur nom."),
    "spreken": ("parler", "Je parlais néerlandais avec elle.", "Nous nous sommes donnés rendez-vous à la gare."),
    "luisteren": ("écouter", "Tu écoutais la radio.", "Elles écoutaient le professeur."),
    "praten": ("discuter", "Je parlais avec le voisin.", "Nous avons parlé des heures de politique."),
    "bellen": ("téléphoner", "Je t'ai appelé hier.", "Elles appelaient chaque semaine."),
    "zoeken": ("chercher", "Il cherchait sa clé.", "Elles cherchaient une solution."),
    "krijgen": ("recevoir", "J'ai reçu un message.", "Nous avons reçu une bonne nouvelle."),
    "gebruiken": ("utiliser", "Tu as utilisé mon stylo.", "Elles ont utilisé de vieilles cartes."),
    "proberen": ("essayer", "J'ai réessayé.", "Nous avons essayé de rester calmes."),
    "hopen": ("espérer", "J'espérais beau temps.", "Elles espéraient un meilleur emploi."),
    "geloven": ("croire", "Il croyait son histoire.", "Nous n'y croyions pas."),
    "begrijpen": ("comprendre", "Je ne comprenais pas la question.", "Elles se comprenaient bien."),
    "vergeten": ("oublier", "J'ai oublié mon parapluie.", "Elles ont oublié le rendez-vous."),
    "beginnen": ("commencer", "Il s'est mis à pleuvoir.", "Nous avons commencé à l'heure."),
    "eten": ("manger", "J'ai mangé un sandwich au fromage.", "Nous avons mangé au restaurant ensemble."),
    "drinken": ("boire", "Il buvait son café sans sucre.", "Elles buvaient de l'eau."),
    "slapen": ("dormir", "J'ai mal dormi cette nuit.", "Elles dormaient sur le canapé."),
    "koken": ("cuisiner", "J'ai fait des pâtes.", "Elles ont cuisiné pour douze personnes."),
    "helpen": ("aider", "Il aidait pour les devoirs.", "Nous avons aidé nos voisins."),
    "vragen": ("demander", "J'ai demandé mon chemin.", "Elles ont demandé le prix."),
    "antwoorden": ("répondre", "Tu as répondu au mail.", "Nous avons répondu à toutes les questions."),
    "vertellen": ("raconter", "Elle racontait une histoire.", "Elles ont annoncé la nouvelle."),
    "horen": ("entendre", "J'ai entendu un bruit.", "Elles entendaient de la musique."),
    "noemen": ("nommer", "Il a posé ses conditions.", "Nous avons cité trois options."),
    "kiezen": ("choisir", "J'ai choisi le bleu.", "Elles ont pris un autre itinéraire."),
    "verliezen": ("perdre", "Il a perdu sa clé.", "Elles ont perdu le match."),
    "winnen": ("gagner", "Elle a gagné le prix.", "Elles ont gagné ensemble."),
    "trekken": ("tirer", "J'ai ouvert la porte en tirant.", "Elles tiraient sur la corde."),
    "dragen": ("porter", "Il portait un sac lourd.", "Elles portaient des habits traditionnels."),
    "breken": ("casser", "Le verre s'est cassé.", "Elles ont battu un record."),
    "snijden": ("couper", "J'ai coupé le pain.", "Elles ont coupé les légumes."),
    "vliegen": ("voler", "Il a pris l'avion pour Paris.", "Elles sont d'abord allées à Rome."),
    "zwemmen": ("nager", "J'ai nagé en mer.", "Elles nageaient chaque été."),
    "rijden": ("conduire", "Je suis allé au travail en voiture.", "Elles roulaient trop vite."),
    "fietsen": ("faire du vélo", "Tu faisais du vélo chaque jour.", "Elles allaient à l'école à vélo."),
    "reizen": ("voyager", "Il voyageait beaucoup pour le travail.", "Elles ont voyagé en Europe."),
    "bezoeken": ("rendre visite à", "J'ai rendu visite à ma tante.", "Elles ont visité le musée."),
    "ontmoeten": ("rencontrer", "Nous nous y sommes rencontrés.", "Elles ont revu de vieux amis."),
    "bedanken": ("remercier", "Je l'ai remerciée pour son aide.", "Nous avons remercié tout le monde."),
    "passen": ("aller / convenir", "Le manteau allait parfaitement.", "Les chaussures n'allaient plus."),
    "missen": ("manquer / rater", "J'ai raté le train.", "Elles manquaient leur famille."),
    "wachten": ("attendre", "J'attendais le bus.", "Elles ont attendu une heure."),
    "lijken": ("sembler", "Ça semblait une bonne idée.", "Elles avaient l'air fatiguées."),
    "voelen": ("se sentir", "Je me sentais mieux.", "Elles sentaient le froid."),
    "leven": ("vivre", "Il a vécu longtemps et heureusement.", "Elles vivaient dans la pauvreté."),
    "sterven": ("mourir", "Il est mort l'année dernière.", "Elles sont mortes en paix."),
    "trouwen": ("se marier", "Elle s'est mariée en juin.", "Elles se sont mariées à l'étranger."),
    "lachen": ("rire", "J'ai ri aux éclats.", "Elles riaient de la plaisanterie."),
    "dansen": ("danser", "Il a dansé avec elle.", "Elles ont dansé jusqu'à minuit."),
    "zingen": ("chanter", "J'ai chanté une chanson.", "Elles chantaient ensemble dans le chœur."),
    "springen": ("sauter", "Il a sauté par-dessus la flaque.", "Elles ont sauté du plongeoir."),
    "vallen": ("tomber", "Je suis tombé sur la glace.", "Elles ont failli tomber."),
    "opstaan": ("se lever", "Je me suis levé tôt.", "Elles se sont levées tard."),
    "aankomen": ("arriver", "Le train est arrivé en retard.", "Elles sont arrivées sans encombre."),
    "weggaan": ("partir", "Il est parti discrètement.", "Elles sont parties sans dire au revoir."),
    "meenemen": ("emporter", "J'ai pris mon ordinateur portable.", "Elles ont apporté des snacks."),
    "verstaan": ("comprendre (parler)", "Je ne le comprenais pas.", "Elles ne se comprenaient pas."),
    "herinneren": ("se souvenir", "Il rappelait la date.", "Elles se souvenaient de tout."),
    "oefenen": ("s'entraîner", "Je m'entraînais chaque jour.", "Elles répétaient pour le concert."),
    "dromen": ("rêver", "Je rêvais de vacances.", "Elles rêvaient de réussir."),
    "bestellen": ("commander", "J'ai commandé un café.", "Elles ont commandé trois pizzas."),
    "bereiken": ("atteindre", "Il a atteint son objectif.", "Elles ont atteint le sommet."),
    "beslissen": ("décider", "Elle a décidé seule.", "Elles ont décidé ensemble."),
    "bouwen": ("construire", "Nous avons construit une remise.", "Elles ont construit une nouvelle maison."),
}
