# ruff: noqa: E501
# 100 high-frequency Dutch verbs (infinitives), numbered 101–200; no overlap with cards 1–100.

VERBS = [
    (
        "openen",
        "to open",
        "ouvrir",
        "heeft/hebben geopend",
        "opende · openden",
        "Ik heb het raam geopend.",
        "I have opened the window.",
        "J'ai ouvert la fenêtre.",
        "Wij hebben de deuren geopend.",
        "We have opened the doors.",
        "Nous avons ouvert les portes.",
        "Hij opende het raam.",
        "He opened the window.",
        "Il a ouvert la fenêtre.",
        "Zij openden de deuren.",
        "They opened the doors.",
        "Elles ont ouvert les portes.",
    ),
    (
        "sluiten",
        "to close",
        "fermer",
        "heeft/hebben gesloten",
        "sloot · sloten",
        "Ik heb de deur gesloten.",
        "I have closed the door.",
        "J'ai fermé la porte.",
        "Zij hebben de winkel gesloten.",
        "They have closed the shop.",
        "Elles ont fermé le magasin.",
        "Hij sloot de deur.",
        "He closed the door.",
        "Il a fermé la porte.",
        "Zij sloten de winkel.",
        "They closed the shop.",
        "Elles ont fermé le magasin.",
    ),
    (
        "sturen",
        "to send",
        "envoyer",
        "heeft/hebben gestuurd",
        "stuurde · stuurden",
        "Ik heb een e-mail gestuurd.",
        "I have sent an email.",
        "J'ai envoyé un e-mail.",
        "Wij hebben kaarten gestuurd.",
        "We have sent cards.",
        "Nous avons envoyé des cartes.",
        "Zij stuurde een bericht.",
        "She sent a message.",
        "Elle a envoyé un message.",
        "Zij stuurden kaarten.",
        "They sent cards.",
        "Elles ont envoyé des cartes.",
    ),
    (
        "ontvangen",
        "to receive",
        "recevoir",
        "heeft/hebben ontvangen",
        "ontving · ontvingen",
        "Ik heb het pakket ontvangen.",
        "I have received the parcel.",
        "J'ai reçu le colis.",
        "Wij hebben veel complimenten ontvangen.",
        "We have received many compliments.",
        "Nous avons reçu beaucoup de compliments.",
        "Hij ontving een brief.",
        "He received a letter.",
        "Il a reçu une lettre.",
        "Zij ontvingen veel post.",
        "They received a lot of mail.",
        "Elles ont reçu beaucoup de courrier.",
    ),
    (
        "betekenen",
        "to mean",
        "signifier",
        "heeft/hebben betekend",
        "betekende · betekenden",
        "Dat heeft weinig betekend.",
        "That has meant little.",
        "Cela a peu signifié.",
        "Deze woorden hebben veel betekend.",
        "These words have meant a lot.",
        "Ces mots ont beaucoup signifié.",
        "Het betekende niets voor hem.",
        "It meant nothing to him.",
        "Cela ne signifiait rien pour lui.",
        "De cijfers betekenden veel.",
        "The figures meant a lot.",
        "Les chiffres signifiaient beaucoup.",
    ),
    (
        "volgen",
        "to follow",
        "suivre",
        "heeft/hebben gevolgd",
        "volgde · volgden",
        "Ik heb een cursus gevolgd.",
        "I have followed a course.",
        "J'ai suivi un cours.",
        "Zij hebben de route gevolgd.",
        "They have followed the route.",
        "Elles ont suivi l'itinéraire.",
        "Hij volgde de instructies.",
        "He followed the instructions.",
        "Il a suivi les instructions.",
        "Zij volgden de gids.",
        "They followed the guide.",
        "Elles ont suivi le guide.",
    ),
    (
        "leiden",
        "to lead",
        "mener",
        "heeft/hebben geleid",
        "leidde · leidden",
        "Zij heeft het team geleid.",
        "She has led the team.",
        "Elle a dirigé l'équipe.",
        "Zij hebben het project geleid.",
        "They have led the project.",
        "Elles ont mené le projet.",
        "Hij leidde de vergadering.",
        "He led the meeting.",
        "Il a dirigé la réunion.",
        "Zij leidden de discussie.",
        "They led the discussion.",
        "Elles ont mené la discussion.",
    ),
    (
        "zorgen",
        "to take care / to ensure",
        "s'occuper / veiller à",
        "heeft/hebben gezorgd",
        "zorgde · zorgden",
        "Ik heb voor de kinderen gezorgd.",
        "I have taken care of the children.",
        "Je me suis occupé des enfants.",
        "Wij hebben voor veiligheid gezorgd.",
        "We have ensured safety.",
        "Nous avons veillé à la sécurité.",
        "Zij zorgde voor eten.",
        "She provided food.",
        "Elle s'est occupée de la nourriture.",
        "Zij zorgden voor orde.",
        "They maintained order.",
        "Elles ont maintenu l'ordre.",
    ),
    (
        "verschijnen",
        "to appear",
        "apparaître",
        "is/zijn verschenen",
        "verscheen · verschenen",
        "Hij is plotseling verschenen.",
        "He has appeared suddenly.",
        "Il est apparu soudain.",
        "Zij zijn in de krant verschenen.",
        "They have appeared in the newspaper.",
        "Elles sont apparues dans le journal.",
        "Het artikel verscheen gisteren.",
        "The article appeared yesterday.",
        "L'article est paru hier.",
        "De foto's verschenen online.",
        "The photos appeared online.",
        "Les photos sont apparues en ligne.",
    ),
    (
        "verdwijnen",
        "to disappear",
        "disparaître",
        "is/zijn verdwenen",
        "verdween · verdwenen",
        "De zon is achter de wolken verdwenen.",
        "The sun has disappeared behind the clouds.",
        "Le soleil a disparu derrière les nuages.",
        "De sporen zijn verdwenen.",
        "The traces have disappeared.",
        "Les traces ont disparu.",
        "Het geluid verdween langzaam.",
        "The sound slowly disappeared.",
        "Le bruit a disparu lentement.",
        "De kinderen verdwenen in de menigte.",
        "The children disappeared into the crowd.",
        "Les enfants ont disparu dans la foule.",
    ),
    (
        "veranderen",
        "to change",
        "changer",
        "heeft/hebben veranderd",
        "veranderde · veranderden",
        "Ik heb van baan veranderd.",
        "I have changed jobs.",
        "J'ai changé de travail.",
        "Zij hebben van plan veranderd.",
        "They have changed their plan.",
        "Elles ont changé de plan.",
        "Hij veranderde van mening.",
        "He changed his mind.",
        "Il a changé d'avis.",
        "Zij veranderden het rooster.",
        "They changed the schedule.",
        "Elles ont changé l'horaire.",
    ),
    (
        "stoppen",
        "to stop",
        "arrêter",
        "heeft/hebben gestopt",
        "stopte · stopten",
        "De bus heeft gestopt.",
        "The bus has stopped.",
        "Le bus s'est arrêté.",
        "Zij hebben met roken gestopt.",
        "They have stopped smoking.",
        "Elles ont arrêté de fumer.",
        "Hij stopte bij het licht.",
        "He stopped at the light.",
        "Il s'est arrêté au feu.",
        "Zij stopten voor de grens.",
        "They stopped before the border.",
        "Elles se sont arrêtées avant la frontière.",
    ),
    (
        "starten",
        "to start",
        "démarrer",
        "heeft/hebben gestart",
        "startte · startten",
        "Het programma heeft gestart.",
        "The program has started.",
        "Le programme a démarré.",
        "Zij hebben de motor gestart.",
        "They have started the engine.",
        "Elles ont démarré le moteur.",
        "De wedstrijd startte laat.",
        "The match started late.",
        "Le match a commencé tard.",
        "De computers startten automatisch.",
        "The computers started automatically.",
        "Les ordinateurs ont démarré automatiquement.",
    ),
    (
        "vullen",
        "to fill",
        "remplir",
        "heeft/hebben gevuld",
        "vulde · vulden",
        "Ik heb het formulier ingevuld.",
        "I have filled in the form.",
        "J'ai rempli le formulaire.",
        "Zij hebben de tank gevuld.",
        "They have filled the tank.",
        "Elles ont fait le plein.",
        "Hij vulde het glas.",
        "He filled the glass.",
        "Il a rempli le verre.",
        "Zij vulden de dozen.",
        "They filled the boxes.",
        "Elles ont rempli les cartons.",
    ),
    (
        "legen",
        "to empty",
        "vider",
        "heeft/hebben geleegd",
        "leegde · leegden",
        "Ik heb de prullenbak geleegd.",
        "I have emptied the bin.",
        "J'ai vidé la poubelle.",
        "Zij hebben de kelder geleegd.",
        "They have emptied the cellar.",
        "Elles ont vidé la cave.",
        "Hij leegde zijn tas.",
        "He emptied his bag.",
        "Il a vidé son sac.",
        "Zij leegden de flessen.",
        "They emptied the bottles.",
        "Elles ont vidé les bouteilles.",
    ),
    (
        "scheiden",
        "to separate / to divorce",
        "séparer / divorcer",
        "heeft/hebben gescheiden",
        "scheidde · scheidden",
        "Ik heb het mengsel gescheiden.",
        "I have separated the mixture.",
        "J'ai séparé le mélange.",
        "Zij hebben de documenten gescheiden.",
        "They have separated the documents.",
        "Elles ont séparé les documents.",
        "Hij scheidde de eieren.",
        "He separated the eggs.",
        "Il a séparé les œufs.",
        "Zij scheidden het afval.",
        "They separated the waste.",
        "Elles ont trié les déchets.",
    ),
    (
        "ruiken",
        "to smell",
        "sentir",
        "heeft/hebben geroken",
        "rook · roken",
        "Ik heb verse broodjes geroken.",
        "I have smelled fresh rolls.",
        "J'ai senti des petits pains frais.",
        "Zij hebben parfum geroken.",
        "They have smelled perfume.",
        "Elles ont senti le parfum.",
        "Het rook naar koffie.",
        "It smelled of coffee.",
        "Ça sentait le café.",
        "De bloemen roken zoet.",
        "The flowers smelled sweet.",
        "Les fleurs sentaient bon.",
    ),
    (
        "proeven",
        "to taste / try",
        "goûter",
        "heeft/hebben geproefd",
        "proefde · proefden",
        "Ik heb de soep geproefd.",
        "I have tasted the soup.",
        "J'ai goûté la soupe.",
        "Wij hebben alle gerechten geproefd.",
        "We have tasted all the dishes.",
        "Nous avons goûté tous les plats.",
        "Zij proefde de wijn.",
        "She tasted the wine.",
        "Elle a goûté le vin.",
        "Zij proefden het dessert.",
        "They tasted the dessert.",
        "Elles ont goûté le dessert.",
    ),
    (
        "smaken",
        "to taste (good)",
        "avoir bon goût",
        "heeft/hebben gesmaakt",
        "smaakte · smaakten",
        "Het heeft lekker gesmaakt.",
        "It has tasted good.",
        "C'était délicieux.",
        "De gerechten hebben uitstekend gesmaakt.",
        "The dishes have tasted excellent.",
        "Les plats étaient excellents.",
        "De taart smaakte zoet.",
        "The cake tasted sweet.",
        "Le gâteau était sucré.",
        "De bonbons smaakten naar mint.",
        "The sweets tasted of mint.",
        "Les bonbons avaient goût de menthe.",
    ),
    (
        "klimmen",
        "to climb",
        "grimper",
        "is/zijn geklommen",
        "klom · klommen",
        "Ik ben op de ladder geklommen.",
        "I have climbed the ladder.",
        "Je suis monté sur l'échelle.",
        "Zij zijn naar de top geklommen.",
        "They have climbed to the top.",
        "Elles sont montées au sommet.",
        "Hij klom voorzichtig.",
        "He climbed carefully.",
        "Il a grimpé prudemment.",
        "De kinderen klommen in de boom.",
        "The children climbed the tree.",
        "Les enfants ont grimpé à l'arbre.",
    ),
    (
        "duiken",
        "to dive",
        "plonger",
        "is/zijn gedoken",
        "dook · duiken",
        "Ik ben in het zwembad gedoken.",
        "I have dived into the pool.",
        "Je me suis plongé dans la piscine.",
        "Zij zijn van de brug gedoken.",
        "They have dived off the bridge.",
        "Elles se sont jetées du pont.",
        "Hij dook naar de bodem.",
        "He dived to the bottom.",
        "Il a plongé vers le fond.",
        "Zij doken elke zomer.",
        "They went diving every summer.",
        "Elles plongeaient chaque été.",
    ),
    (
        "scheren",
        "to shave / shear",
        "raser / tondre",
        "heeft/hebben geschoren",
        "schoor · schoren",
        "Ik heb me geschoren.",
        "I have shaved.",
        "Je me suis rasé.",
        "Zij hebben de schapen geschoren.",
        "They have sheared the sheep.",
        "Elles ont tondu les moutons.",
        "Hij schoor zijn baard.",
        "He shaved his beard.",
        "Il s'est rasé la barbe.",
        "Zij schoren het gras.",
        "They mowed the grass.",
        "Elles ont tondu la pelouse.",
    ),
    (
        "vergelijken",
        "to compare",
        "comparer",
        "heeft/hebben vergeleken",
        "vergeleek · vergeleken",
        "Ik heb de prijzen vergeleken.",
        "I have compared the prices.",
        "J'ai comparé les prix.",
        "Zij hebben de modellen vergeleken.",
        "They have compared the models.",
        "Elles ont comparé les modèles.",
        "Hij vergeleek de cijfers.",
        "He compared the figures.",
        "Il a comparé les chiffres.",
        "Zij vergeleken de resultaten.",
        "They compared the results.",
        "Elles ont comparé les résultats.",
    ),
    (
        "uitleggen",
        "to explain",
        "expliquer",
        "heeft/hebben uitgelegd",
        "legde uit · legden uit",
        "Ik heb de regels uitgelegd.",
        "I have explained the rules.",
        "J'ai expliqué les règles.",
        "Zij hebben het plan uitgelegd.",
        "They have explained the plan.",
        "Elles ont expliqué le plan.",
        "De leraar legde de opdracht uit.",
        "The teacher explained the assignment.",
        "Le professeur a expliqué le devoir.",
        "Zij legden de procedure uit.",
        "They explained the procedure.",
        "Elles ont expliqué la procédure.",
    ),
    (
        "voorstellen",
        "to introduce / propose",
        "présenter / proposer",
        "heeft/hebben voorgesteld",
        "stelde voor · stelden voor",
        "Ik heb een idee voorgesteld.",
        "I have proposed an idea.",
        "J'ai proposé une idée.",
        "Zij hebben zich voorgesteld.",
        "They have introduced themselves.",
        "Elles se sont présentées.",
        "Hij stelde zijn vriendin voor.",
        "He introduced his girlfriend.",
        "Il a présenté sa copine.",
        "Zij stelden een motie voor.",
        "They proposed a motion.",
        "Elles ont proposé une motion.",
    ),
    (
        "verwachten",
        "to expect",
        "s'attendre à",
        "heeft/hebben verwacht",
        "verwachtte · verwachtten",
        "Ik heb dit niet verwacht.",
        "I did not expect this.",
        "Je ne m'attendais pas à cela.",
        "Zij hebben goed nieuws verwacht.",
        "They expected good news.",
        "Elles s'attendaient à une bonne nouvelle.",
        "Hij verwachtte vertraging.",
        "He expected a delay.",
        "Il s'attendait à un retard.",
        "Zij verwachtten regen.",
        "They expected rain.",
        "Elles s'attendaient à de la pluie.",
    ),
    (
        "regelen",
        "to arrange / fix",
        "régler",
        "heeft/hebben geregeld",
        "regelde · regelden",
        "Ik heb de betaling geregeld.",
        "I have arranged the payment.",
        "J'ai réglé le paiement.",
        "Zij hebben de verzekering geregeld.",
        "They have arranged the insurance.",
        "Elles ont réglé l'assurance.",
        "Hij regelde een taxi.",
        "He arranged a taxi.",
        "Il a commandé un taxi.",
        "Zij regelden de logistiek.",
        "They arranged the logistics.",
        "Elles ont organisé la logistique.",
    ),
    (
        "controleren",
        "to check",
        "contrôler",
        "heeft/hebben gecontroleerd",
        "controleerde · controleerden",
        "Ik heb de banden gecontroleerd.",
        "I have checked the tyres.",
        "J'ai contrôlé les pneus.",
        "Zij hebben de toegang gecontroleerd.",
        "They have checked access.",
        "Elles ont contrôlé l'accès.",
        "De beveiliging controleerde de tassen.",
        "Security checked the bags.",
        "La sécurité a contrôlé les sacs.",
        "Zij controleerden de lijsten.",
        "They checked the lists.",
        "Elles ont contrôlé les listes.",
    ),
    (
        "uitnodigen",
        "to invite",
        "inviter",
        "heeft/hebben uitgenodigd",
        "nodigde uit · nodigden uit",
        "Ik heb vrienden uitgenodigd.",
        "I have invited friends.",
        "J'ai invité des amis.",
        "Zij hebben collega's uitgenodigd.",
        "They have invited colleagues.",
        "Elles ont invité des collègues.",
        "Hij nodigde ons uit voor het diner.",
        "He invited us to dinner.",
        "Il nous a invités à dîner.",
        "Zij nodigden de buren uit.",
        "They invited the neighbours.",
        "Elles ont invité les voisins.",
    ),
    (
        "accepteren",
        "to accept",
        "accepter",
        "heeft/hebben geaccepteerd",
        "accepteerde · accepteerden",
        "Ik heb het aanbod geaccepteerd.",
        "I have accepted the offer.",
        "J'ai accepté l'offre.",
        "Zij hebben de voorwaarden geaccepteerd.",
        "They have accepted the conditions.",
        "Elles ont accepté les conditions.",
        "Hij accepteerde de uitnodiging.",
        "He accepted the invitation.",
        "Il a accepté l'invitation.",
        "Zij accepteerden het voorstel.",
        "They accepted the proposal.",
        "Elles ont accepté la proposition.",
    ),
    (
        "weigeren",
        "to refuse",
        "refuser",
        "heeft/hebben geweigerd",
        "weigerde · weigerden",
        "Ik heb hulp geweigerd.",
        "I have refused help.",
        "J'ai refusé de l'aide.",
        "Zij hebben betaling geweigerd.",
        "They have refused payment.",
        "Elles ont refusé le paiement.",
        "Hij weigerde te tekenen.",
        "He refused to sign.",
        "Il a refusé de signer.",
        "Zij weigerden toegang.",
        "They refused access.",
        "Elles ont refusé l'accès.",
    ),
    (
        "aanbieden",
        "to offer",
        "offrir",
        "heeft/hebben aangeboden",
        "bood aan · boden aan",
        "Ik heb koffie aangeboden.",
        "I have offered coffee.",
        "J'ai offert du café.",
        "Zij hebben een korting aangeboden.",
        "They have offered a discount.",
        "Elles ont offert une réduction.",
        "Hij bood zijn hulp aan.",
        "He offered his help.",
        "Il a offert son aide.",
        "Zij boden een contract aan.",
        "They offered a contract.",
        "Elles ont proposé un contrat.",
    ),
    (
        "deelnemen",
        "to participate",
        "participer",
        "heeft/hebben deelgenomen",
        "nam deel · namen deel",
        "Ik heb aan de enquête deelgenomen.",
        "I have taken part in the survey.",
        "J'ai participé à l'enquête.",
        "Zij hebben aan het toernooi deelgenomen.",
        "They have participated in the tournament.",
        "Elles ont participé au tournoi.",
        "Hij nam deel aan de cursus.",
        "He took part in the course.",
        "Il a participé au cours.",
        "Zij namen deel aan de discussie.",
        "They took part in the discussion.",
        "Elles ont participé à la discussion.",
    ),
    (
        "bepalen",
        "to determine",
        "déterminer",
        "heeft/hebben bepaald",
        "bepaalde · bepaalden",
        "De jury heeft de winnaar bepaald.",
        "The jury has determined the winner.",
        "Le jury a déterminé le gagnant.",
        "Zij hebben de prijs bepaald.",
        "They have set the price.",
        "Elles ont fixé le prix.",
        "Het weer bepaalde onze plannen.",
        "The weather determined our plans.",
        "Le temps a déterminé nos plans.",
        "De regels bepaalden het verloop.",
        "The rules determined the course.",
        "Les règles ont déterminé le déroulement.",
    ),
    (
        "beperken",
        "to limit",
        "limiter",
        "heeft/hebben beperkt",
        "beperkte · beperkten",
        "Ik heb de schade beperkt.",
        "I have limited the damage.",
        "J'ai limité les dégâts.",
        "Zij hebben de kosten beperkt.",
        "They have limited the costs.",
        "Elles ont limité les coûts.",
        "Hij beperkte het aantal plaatsen.",
        "He limited the number of seats.",
        "Il a limité le nombre de places.",
        "Zij beperkten de snelheid.",
        "They limited the speed.",
        "Elles ont limité la vitesse.",
    ),
    (
        "repareren",
        "to repair",
        "réparer",
        "heeft/hebben gerepareerd",
        "repareerde · repareerden",
        "Ik heb de fiets gerepareerd.",
        "I have repaired the bike.",
        "J'ai réparé le vélo.",
        "Zij hebben het dak gerepareerd.",
        "They have repaired the roof.",
        "Elles ont réparé le toit.",
        "Hij repareerde de computer.",
        "He repaired the computer.",
        "Il a réparé l'ordinateur.",
        "Zij repareerden de leiding.",
        "They repaired the pipe.",
        "Elles ont réparé la canalisation.",
    ),
    (
        "verbeteren",
        "to improve",
        "améliorer",
        "heeft/hebben verbeterd",
        "verbeterde · verbeterden",
        "Ik heb mijn Nederlands verbeterd.",
        "I have improved my Dutch.",
        "J'ai amélioré mon néerlandais.",
        "Zij hebben de service verbeterd.",
        "They have improved the service.",
        "Elles ont amélioré le service.",
        "Het bedrijf verbeterde de kwaliteit.",
        "The company improved the quality.",
        "L'entreprise a amélioré la qualité.",
        "Zij verbeterden het ontwerp.",
        "They improved the design.",
        "Elles ont amélioré le design.",
    ),
    (
        "verminderen",
        "to reduce",
        "réduire",
        "heeft/hebben verminderd",
        "verminderde · verminderden",
        "Wij hebben het gebruik verminderd.",
        "We have reduced use.",
        "Nous avons réduit l'utilisation.",
        "Zij hebben de uitstoot verminderd.",
        "They have reduced emissions.",
        "Elles ont réduit les émissions.",
        "De prijs verminderde snel.",
        "The price decreased quickly.",
        "Le prix a vite baissé.",
        "De voorraden verminderden.",
        "The supplies diminished.",
        "Les stocks ont diminué.",
    ),
    (
        "verhogen",
        "to increase",
        "augmenter",
        "heeft/hebben verhoogd",
        "verhoogde · verhoogden",
        "Zij heeft de huur verhoogd.",
        "She has increased the rent.",
        "Elle a augmenté le loyer.",
        "Zij hebben de beloning verhoogd.",
        "They have increased the reward.",
        "Elles ont augmenté la récompense.",
        "De bank verhoogde de rente.",
        "The bank raised the interest rate.",
        "La banque a augmenté le taux.",
        "Zij verhoogden de druk.",
        "They increased the pressure.",
        "Elles ont augmenté la pression.",
    ),
    (
        "besparen",
        "to save (money, energy)",
        "économiser",
        "heeft/hebben bespaard",
        "bespaarde · bespaarden",
        "Ik heb water bespaard.",
        "I have saved water.",
        "J'ai économisé de l'eau.",
        "Zij hebben energie bespaard.",
        "They have saved energy.",
        "Elles ont économisé de l'énergie.",
        "Hij bespaarde op brandstof.",
        "He saved on fuel.",
        "Il a économisé du carburant.",
        "Zij bespaarden kosten.",
        "They saved costs.",
        "Elles ont réduit les coûts.",
    ),
    (
        "uitgeven",
        "to spend / publish",
        "dépenser / publier",
        "heeft/hebben uitgegeven",
        "gaf uit · gaven uit",
        "Ik heb te veel uitgegeven.",
        "I have spent too much.",
        "J'ai trop dépensé.",
        "Zij hebben een boek uitgegeven.",
        "They have published a book.",
        "Elles ont publié un livre.",
        "Hij gaf geld uit aan eten.",
        "He spent money on food.",
        "Il a dépensé de l'argent pour la nourriture.",
        "Zij gaven veel uit aan reizen.",
        "They spent a lot on travel.",
        "Elles ont beaucoup dépensé en voyages.",
    ),
    (
        "sparen",
        "to save money",
        "épargner",
        "heeft/hebben gespaard",
        "spaarde · spaarden",
        "Ik heb voor later gespaard.",
        "I have saved for later.",
        "J'ai épargné pour plus tard.",
        "Zij hebben voor een huis gespaard.",
        "They have saved for a house.",
        "Elles ont épargné pour une maison.",
        "Hij spaarde elke maand.",
        "He saved every month.",
        "Il épargnait chaque mois.",
        "Zij spaarden voor hun kinderen.",
        "They saved for their children.",
        "Elles épargnaient pour leurs enfants.",
    ),
    (
        "lenen",
        "to borrow / lend",
        "emprunter / prêter",
        "heeft/hebben geleend",
        "leende · leenden",
        "Ik heb geld geleend.",
        "I have borrowed money.",
        "J'ai emprunté de l'argent.",
        "Zij hebben boeken geleend.",
        "They have borrowed books.",
        "Elles ont emprunté des livres.",
        "Hij leende de auto.",
        "He borrowed the car.",
        "Il a emprunté la voiture.",
        "Zij leenden gereedschap.",
        "They borrowed tools.",
        "Elles ont emprunté des outils.",
    ),
    (
        "huren",
        "to rent",
        "louer",
        "heeft/hebben gehuurd",
        "huurde · huurden",
        "Ik heb een auto gehuurd.",
        "I have rented a car.",
        "J'ai loué une voiture.",
        "Zij hebben een appartement gehuurd.",
        "They have rented a flat.",
        "Elles ont loué un appartement.",
        "Wij huurden een boot.",
        "We rented a boat.",
        "Nous avons loué un bateau.",
        "Zij huurden fietsen.",
        "They rented bikes.",
        "Elles ont loué des vélos.",
    ),
    (
        "verhuren",
        "to let out",
        "louer (à quelqu'un)",
        "heeft/hebben verhuurd",
        "verhuurde · verhuurden",
        "Ik heb mijn kamer verhuurd.",
        "I have let my room.",
        "J'ai loué ma chambre.",
        "Zij hebben het pand verhuurd.",
        "They have let the property.",
        "Elles ont loué le bien.",
        "Hij verhuurde zijn garage.",
        "He let his garage.",
        "Il a loué son garage.",
        "Zij verhuurden stallen.",
        "They let stables.",
        "Elles ont loué des boxes.",
    ),
    (
        "tonen",
        "to show",
        "montrer",
        "heeft/hebben getoond",
        "toonde · toonden",
        "Het scherm heeft het resultaat getoond.",
        "The screen has shown the result.",
        "L'écran a montré le résultat.",
        "Zij hebben moed getoond.",
        "They have shown courage.",
        "Elles ont montré du courage.",
        "Hij toonde een kaart.",
        "He showed a map.",
        "Il a montré une carte.",
        "Zij toonden interesse.",
        "They showed interest.",
        "Elles ont montré de l'intérêt.",
    ),
    (
        "verpakken",
        "to pack",
        "emballer",
        "heeft/hebben verpakt",
        "verpakte · verpakten",
        "Ik heb het cadeau verpakt.",
        "I have wrapped the present.",
        "J'ai emballé le cadeau.",
        "Zij hebben de dozen verpakt.",
        "They have packed the boxes.",
        "Elles ont emballé les cartons.",
        "Hij verpakte de flessen.",
        "He packed the bottles.",
        "Il a emballé les bouteilles.",
        "Zij verpakten voorzichtig.",
        "They packed carefully.",
        "Elles ont emballé avec soin.",
    ),
    (
        "verzenden",
        "to send (post)",
        "expédier",
        "heeft/hebben verzonden",
        "verzond · verzonden",
        "Ik heb het pakket verzonden.",
        "I have sent the parcel.",
        "J'ai expédié le colis.",
        "Zij hebben de documenten verzonden.",
        "They have sent the documents.",
        "Elles ont expédié les documents.",
        "Het bedrijf verzond de bestelling.",
        "The company shipped the order.",
        "L'entreprise a expédié la commande.",
        "Zij verzonden per koerier.",
        "They sent by courier.",
        "Elles ont envoyé par coursier.",
    ),
    (
        "behouden",
        "to keep / retain",
        "conserver",
        "heeft/hebben behouden",
        "behield · behielden",
        "Wij hebben onze vrijheid behouden.",
        "We have kept our freedom.",
        "Nous avons conservé notre liberté.",
        "Zij hebben het record behouden.",
        "They have kept the record.",
        "Elles ont conservé le record.",
        "Hij behield zijn kalmte.",
        "He kept his calm.",
        "Il a gardé son calme.",
        "Zij behielden hun voorsprong.",
        "They kept their lead.",
        "Elles ont conservé leur avance.",
    ),
    (
        "voortzetten",
        "to continue",
        "poursuivre",
        "heeft/hebben voortgezet",
        "zette voort · zetten voort",
        "Wij hebben het werk voortgezet.",
        "We have continued the work.",
        "Nous avons poursuivi le travail.",
        "Zij hebben het beleid voortgezet.",
        "They have continued the policy.",
        "Elles ont poursuivi la politique.",
        "Hij zette het project voort.",
        "He continued the project.",
        "Il a poursuivi le projet.",
        "Zij zetten de strijd voort.",
        "They continued the fight.",
        "Elles ont poursuivi le combat.",
    ),
    (
        "opruimen",
        "to tidy up",
        "ranger",
        "heeft/hebben opgeruimd",
        "ruimde op · ruimden op",
        "Ik heb de keuken opgeruimd.",
        "I have tidied the kitchen.",
        "J'ai rangé la cuisine.",
        "Zij hebben de zolder opgeruimd.",
        "They have cleared the attic.",
        "Elles ont rangé le grenier.",
        "Hij ruimde de tafel op.",
        "He cleared the table.",
        "Il a débarrassé la table.",
        "Zij ruimden de schuur op.",
        "They tidied the shed.",
        "Elles ont rangé la remise.",
    ),
    (
        "schoonmaken",
        "to clean",
        "nettoyer",
        "heeft/hebben schoongemaakt",
        "maakte schoon · maakten schoon",
        "Ik heb de badkamer schoongemaakt.",
        "I have cleaned the bathroom.",
        "J'ai nettoyé la salle de bain.",
        "Zij hebben de ramen schoongemaakt.",
        "They have cleaned the windows.",
        "Elles ont nettoyé les fenêtres.",
        "Zij maakte de vloer schoon.",
        "She cleaned the floor.",
        "Elle a nettoyé le sol.",
        "Zij maakten de auto schoon.",
        "They cleaned the car.",
        "Elles ont nettoyé la voiture.",
    ),
    (
        "wassen",
        "to wash",
        "laver",
        "heeft/hebben gewassen",
        "waste · wasten",
        "Ik heb de auto gewassen.",
        "I have washed the car.",
        "J'ai lavé la voiture.",
        "Zij hebben de kleren gewassen.",
        "They have washed the clothes.",
        "Elles ont lavé le linge.",
        "Hij waste zijn handen.",
        "He washed his hands.",
        "Il s'est lavé les mains.",
        "Zij wasten het servies.",
        "They washed the dishes.",
        "Elles ont lavé la vaisselle.",
    ),
    (
        "strijken",
        "to iron",
        "repasser",
        "heeft/hebben gestreken",
        "streek · streken",
        "Ik heb het overhemd gestreken.",
        "I have ironed the shirt.",
        "J'ai repassé la chemise.",
        "Zij hebben de gordijnen gestreken.",
        "They have ironed the curtains.",
        "Elles ont repassé les rideaux.",
        "Hij streek de broek.",
        "He ironed the trousers.",
        "Il a repassé le pantalon.",
        "Zij streken de lakens.",
        "They ironed the sheets.",
        "Elles ont repassé les draps.",
    ),
    (
        "opwarmen",
        "to heat up",
        "réchauffer",
        "heeft/hebben opgewarmd",
        "warmde op · warmden op",
        "Ik heb de soep opgewarmd.",
        "I have heated up the soup.",
        "J'ai réchauffé la soupe.",
        "Zij hebben de oven opgewarmd.",
        "They have preheated the oven.",
        "Elles ont préchauffé le four.",
        "Hij warmde de kamer op.",
        "He warmed the room.",
        "Il a réchauffé la pièce.",
        "Zij warmden het eten op.",
        "They warmed the food.",
        "Elles ont réchauffé le repas.",
    ),
    (
        "afkoelen",
        "to cool down",
        "refroidir",
        "heeft/hebben afgekoeld",
        "koelde af · koelden af",
        "De motor is afgekoeld.",
        "The engine has cooled down.",
        "Le moteur a refroidi.",
        "Zij hebben de drank afgekoeld.",
        "They have chilled the drinks.",
        "Elles ont refroidi les boissons.",
        "Het koelde snel af.",
        "It cooled down quickly.",
        "Ça a vite refroidi.",
        "De temperaturen koelden af.",
        "The temperatures cooled.",
        "Les températures ont baissé.",
    ),
    (
        "voeden",
        "to feed",
        "nourrir",
        "heeft/hebben gevoed",
        "voedde · voedden",
        "Ik heb de kat gevoed.",
        "I have fed the cat.",
        "J'ai nourri le chat.",
        "Zij hebben de baby's gevoed.",
        "They have fed the babies.",
        "Elles ont nourri les bébés.",
        "Zij voedde de honden.",
        "She fed the dogs.",
        "Elle a nourri les chiens.",
        "Zij voedden de dieren.",
        "They fed the animals.",
        "Elles ont nourri les animaux.",
    ),
    (
        "borstelen",
        "to brush",
        "brosser",
        "heeft/hebben geborsteld",
        "borstelde · borstelden",
        "Ik heb mijn haar geborsteld.",
        "I have brushed my hair.",
        "Je me suis brossé les cheveux.",
        "Zij hebben de hond geborsteld.",
        "They have brushed the dog.",
        "Elles ont brossé le chien.",
        "Hij borstelde zijn jas.",
        "He brushed his coat.",
        "Il a brossé son manteau.",
        "Zij borstelden het paard.",
        "They brushed the horse.",
        "Elles ont brossé le cheval.",
    ),
    (
        "ontdekken",
        "to discover",
        "découvrir",
        "heeft/hebben ontdekt",
        "ontdekte · ontdekten",
        "Ik heb een fout ontdekt.",
        "I have discovered a mistake.",
        "J'ai découvert une erreur.",
        "Zij hebben een eiland ontdekt.",
        "They have discovered an island.",
        "Elles ont découvert une île.",
        "Columbus ontdekte Amerika.",
        "Columbus discovered America.",
        "Colomb a découvert l'Amérique.",
        "Zij ontdekten olie.",
        "They discovered oil.",
        "Elles ont découvert du pétrole.",
    ),
    (
        "beschermen",
        "to protect",
        "protéger",
        "heeft/hebben beschermd",
        "beschermde · beschermden",
        "De dijk heeft de stad beschermd.",
        "The dyke has protected the city.",
        "La digue a protégé la ville.",
        "Zij hebben de kinderen beschermd.",
        "They have protected the children.",
        "Elles ont protégé les enfants.",
        "Hij beschermde zijn ogen.",
        "He protected his eyes.",
        "Il a protégé ses yeux.",
        "Zij beschermden de natuur.",
        "They protected nature.",
        "Elles ont protégé la nature.",
    ),
    (
        "aanvallen",
        "to attack",
        "attaquer",
        "heeft/hebben aangevallen",
        "viel aan · vielen aan",
        "De hond heeft de postbode aangevallen.",
        "The dog has attacked the postman.",
        "Le chien a attaqué le facteur.",
        "Zij hebben de basis aangevallen.",
        "They have attacked the base.",
        "Elles ont attaqué la base.",
        "Hij viel plotseling aan.",
        "He attacked suddenly.",
        "Il a attaqué soudain.",
        "Zij vielen 's nachts aan.",
        "They attacked at night.",
        "Elles ont attaqué la nuit.",
    ),
    (
        "verdedigen",
        "to defend",
        "défendre",
        "heeft/hebben verdedigd",
        "verdedigde · verdedigden",
        "Ik heb mijn mening verdedigd.",
        "I have defended my opinion.",
        "J'ai défendu mon opinion.",
        "Zij hebben de grens verdedigd.",
        "They have defended the border.",
        "Elles ont défendu la frontière.",
        "Hij verdedigde zijn titel.",
        "He defended his title.",
        "Il a défendu son titre.",
        "Zij verdedigden de stad.",
        "They defended the city.",
        "Elles ont défendu la ville.",
    ),
    (
        "verraden",
        "to betray",
        "trahir",
        "heeft/hebben verraden",
        "verraadde · verraden",
        "Hij heeft zijn vriend verraden.",
        "He has betrayed his friend.",
        "Il a trahi son ami.",
        "Zij hebben het vertrouwen verraden.",
        "They have betrayed trust.",
        "Elles ont trahi la confiance.",
        "Zij verraadde het geheim.",
        "She betrayed the secret.",
        "Elle a trahi le secret.",
        "Zij verraadden hun principes.",
        "They betrayed their principles.",
        "Elles ont trahi leurs principes.",
    ),
    (
        "vergeven",
        "to forgive",
        "pardonner",
        "heeft/hebben vergeven",
        "vergaf · vergaven",
        "Ik heb hem vergeven.",
        "I have forgiven him.",
        "Je lui ai pardonné.",
        "Zij hebben elkaar vergeven.",
        "They have forgiven each other.",
        "Elles se sont pardonné.",
        "Hij vergaf haar de fout.",
        "He forgave her the mistake.",
        "Il lui a pardonné l'erreur.",
        "Zij vergaven de schuld.",
        "They forgave the debt.",
        "Elles ont pardonné la dette.",
    ),
    (
        "vermijden",
        "to avoid",
        "éviter",
        "heeft/hebben vermeden",
        "vermeed · vermeden",
        "Ik heb file vermeden.",
        "I have avoided the traffic jam.",
        "J'ai évité les embouteillages.",
        "Zij hebben risico's vermeden.",
        "They have avoided risks.",
        "Elles ont évité les risques.",
        "Hij vermeed de vraag.",
        "He avoided the question.",
        "Il a évité la question.",
        "Zij vermeden conflicten.",
        "They avoided conflicts.",
        "Elles ont évité les conflits.",
    ),
    (
        "ontwikkelen",
        "to develop",
        "développer",
        "heeft/hebben ontwikkeld",
        "ontwikkelde · ontwikkelden",
        "Zij heeft een app ontwikkeld.",
        "She has developed an app.",
        "Elle a développé une appli.",
        "Zij hebben een vaccin ontwikkeld.",
        "They have developed a vaccine.",
        "Elles ont développé un vaccin.",
        "Het bedrijf ontwikkelde nieuwe software.",
        "The company developed new software.",
        "L'entreprise a développé un nouveau logiciel.",
        "Zij ontwikkelden een strategie.",
        "They developed a strategy.",
        "Elles ont développé une stratégie.",
    ),
    (
        "publiceren",
        "to publish",
        "publier",
        "heeft/hebben gepubliceerd",
        "publiceerde · publiceerden",
        "Ik heb een artikel gepubliceerd.",
        "I have published an article.",
        "J'ai publié un article.",
        "Zij hebben een rapport gepubliceerd.",
        "They have published a report.",
        "Elles ont publié un rapport.",
        "De krant publiceerde het nieuws.",
        "The newspaper published the news.",
        "Le journal a publié la nouvelle.",
        "Zij publiceerden cijfers.",
        "They published figures.",
        "Elles ont publié des chiffres.",
    ),
    (
        "downloaden",
        "to download",
        "télécharger",
        "heeft/hebben gedownload",
        "downloadde · downloadden",
        "Ik heb het bestand gedownload.",
        "I have downloaded the file.",
        "J'ai téléchargé le fichier.",
        "Zij hebben de update gedownload.",
        "They have downloaded the update.",
        "Elles ont téléchargé la mise à jour.",
        "Hij downloadde een film.",
        "He downloaded a film.",
        "Il a téléchargé un film.",
        "Zij downloadden muziek.",
        "They downloaded music.",
        "Elles ont téléchargé de la musique.",
    ),
    (
        "uploaden",
        "to upload",
        "téléverser",
        "heeft/hebben geüpload",
        "uploadde · uploadden",
        "Ik heb een foto geüpload.",
        "I have uploaded a photo.",
        "J'ai téléversé une photo.",
        "Zij hebben het document geüpload.",
        "They have uploaded the document.",
        "Elles ont téléversé le document.",
        "Hij uploadde een video.",
        "He uploaded a video.",
        "Il a téléversé une vidéo.",
        "Zij uploadden bestanden.",
        "They uploaded files.",
        "Elles ont téléversé des fichiers.",
    ),
    (
        "printen",
        "to print",
        "imprimer",
        "heeft/hebben geprint",
        "printte · printten",
        "Ik heb het rapport geprint.",
        "I have printed the report.",
        "J'ai imprimé le rapport.",
        "Zij hebben de tickets geprint.",
        "They have printed the tickets.",
        "Elles ont imprimé les billets.",
        "Hij printte de handleiding.",
        "He printed the manual.",
        "Il a imprimé le mode d'emploi.",
        "Zij printten posters.",
        "They printed posters.",
        "Elles ont imprimé des affiches.",
    ),
    (
        "scannen",
        "to scan",
        "scanner",
        "heeft/hebben gescand",
        "scande · scanden",
        "Ik heb de code gescand.",
        "I have scanned the code.",
        "J'ai scanné le code.",
        "Zij hebben de documenten gescand.",
        "They have scanned the documents.",
        "Elles ont scanné les documents.",
        "Hij scande zijn paspoort.",
        "He scanned his passport.",
        "Il a scanné son passeport.",
        "Zij scanden de streepjescode.",
        "They scanned the barcode.",
        "Elles ont scanné le code-barres.",
    ),
    (
        "kopiëren",
        "to copy",
        "copier",
        "heeft/hebben gekopieerd",
        "kopieerde · kopieerden",
        "Ik heb de tekst gekopieerd.",
        "I have copied the text.",
        "J'ai copié le texte.",
        "Zij hebben de bestanden gekopieerd.",
        "They have copied the files.",
        "Elles ont copié les fichiers.",
        "Hij kopieerde het ontwerp.",
        "He copied the design.",
        "Il a copié le design.",
        "Zij kopieerden de lijst.",
        "They copied the list.",
        "Elles ont copié la liste.",
    ),
    (
        "knippen",
        "to cut (with scissors)",
        "couper",
        "heeft/hebben geknipt",
        "knipte · knipten",
        "Ik heb het touw geknipt.",
        "I have cut the rope.",
        "J'ai coupé la corde.",
        "Zij hebben het papier geknipt.",
        "They have cut the paper.",
        "Elles ont coupé le papier.",
        "Hij knipte zijn nagels.",
        "He cut his nails.",
        "Il s'est coupé les ongles.",
        "Zij knipten lint.",
        "They cut ribbon.",
        "Elles ont coupé du ruban.",
    ),
    (
        "plakken",
        "to stick / paste",
        "coller",
        "heeft/hebben geplakt",
        "plakte · plakten",
        "Ik heb een poster geplakt.",
        "I have put up a poster.",
        "J'ai collé une affiche.",
        "Zij hebben etiketten geplakt.",
        "They have stuck on labels.",
        "Elles ont collé des étiquettes.",
        "Hij plakte de envelop dicht.",
        "He sealed the envelope.",
        "Il a collé l'enveloppe.",
        "Zij plakten tape.",
        "They stuck tape.",
        "Elles ont collé du ruban adhésif.",
    ),
    (
        "tekenen",
        "to draw",
        "dessiner",
        "heeft/hebben getekend",
        "tekende · tekenden",
        "Ik heb een schets getekend.",
        "I have drawn a sketch.",
        "J'ai dessiné une esquisse.",
        "Zij hebben een kaart getekend.",
        "They have drawn a map.",
        "Elles ont dessiné une carte.",
        "Hij tekende een huis.",
        "He drew a house.",
        "Il a dessiné une maison.",
        "Zij tekenden portretten.",
        "They drew portraits.",
        "Elles ont dessiné des portraits.",
    ),
    (
        "schilderen",
        "to paint",
        "peindre",
        "heeft/hebben geschilderd",
        "schilderde · schilderden",
        "Ik heb de muur geschilderd.",
        "I have painted the wall.",
        "J'ai peint le mur.",
        "Zij hebben het hek geschilderd.",
        "They have painted the fence.",
        "Elles ont peint la barrière.",
        "Hij schilderde een portret.",
        "He painted a portrait.",
        "Il a peint un portrait.",
        "Zij schilderden het plafond.",
        "They painted the ceiling.",
        "Elles ont peint le plafond.",
    ),
    (
        "fotograferen",
        "to photograph",
        "photographier",
        "heeft/hebben gefotografeerd",
        "fotografeerde · fotografeerden",
        "Ik heb het landschap gefotografeerd.",
        "I have photographed the landscape.",
        "J'ai photographié le paysage.",
        "Zij hebben de bruid gefotografeerd.",
        "They have photographed the bride.",
        "Elles ont photographié la mariée.",
        "Hij fotografeerde vogels.",
        "He photographed birds.",
        "Il a photographié des oiseaux.",
        "Zij fotografeerden het evenement.",
        "They photographed the event.",
        "Elles ont photographié l'événement.",
    ),
    (
        "filmen",
        "to film",
        "filmer",
        "heeft/hebben gefilmd",
        "filmde · filmden",
        "Ik heb de speech gefilmd.",
        "I have filmed the speech.",
        "J'ai filmé le discours.",
        "Zij hebben het concert gefilmd.",
        "They have filmed the concert.",
        "Elles ont filmé le concert.",
        "Hij filmde met zijn telefoon.",
        "He filmed with his phone.",
        "Il a filmé avec son téléphone.",
        "Zij filmden de training.",
        "They filmed the training.",
        "Elles ont filmé l'entraînement.",
    ),
    (
        "opnemen",
        "to record / pick up",
        "enregistrer / prendre",
        "heeft/hebben opgenomen",
        "nam op · namen op",
        "Ik heb het gesprek opgenomen.",
        "I have recorded the conversation.",
        "J'ai enregistré la conversation.",
        "Zij hebben muziek opgenomen.",
        "They have recorded music.",
        "Elles ont enregistré de la musique.",
        "Hij nam de pakketjes op.",
        "He picked up the parcels.",
        "Il a pris les colis.",
        "Zij namen gasten op.",
        "They took guests in.",
        "Elles ont accueilli des invités.",
    ),
    (
        "streamen",
        "to stream",
        "diffuser en streaming",
        "heeft/hebben gestreamd",
        "streamde · streamden",
        "Ik heb de wedstrijd gestreamd.",
        "I have streamed the match.",
        "J'ai diffusé le match en streaming.",
        "Zij hebben een film gestreamd.",
        "They have streamed a film.",
        "Elles ont diffusé un film en streaming.",
        "Hij streamde live.",
        "He streamed live.",
        "Il a diffusé en direct.",
        "Zij streamden muziek.",
        "They streamed music.",
        "Elles ont diffusé de la musique.",
    ),
    (
        "mailen",
        "to email",
        "envoyer un e-mail",
        "heeft/hebben gemaild",
        "mailde · mailden",
        "Ik heb de factuur gemaild.",
        "I have emailed the invoice.",
        "J'ai envoyé la facture par e-mail.",
        "Zij hebben iedereen gemaild.",
        "They have emailed everyone.",
        "Elles ont envoyé un e-mail à tout le monde.",
        "Hij mailde de agenda.",
        "He emailed the agenda.",
        "Il a envoyé l'agenda par e-mail.",
        "Zij mailden de link.",
        "They emailed the link.",
        "Elles ont envoyé le lien par e-mail.",
    ),
    (
        "reageren",
        "to react",
        "réagir",
        "heeft/hebben gereageerd",
        "reageerde · reageerden",
        "Ik heb snel gereageerd.",
        "I have reacted quickly.",
        "J'ai réagi vite.",
        "Zij hebben positief gereageerd.",
        "They have reacted positively.",
        "Elles ont réagi positivement.",
        "Hij reageerde koel.",
        "He reacted coolly.",
        "Il a réagi froidement.",
        "Zij reageerden verbaasd.",
        "They reacted with surprise.",
        "Elles ont réagi avec surprise.",
    ),
    (
        "delen",
        "to share / divide",
        "partager / diviser",
        "heeft/hebben gedeeld",
        "deelde · deelden",
        "Ik heb het nieuws gedeeld.",
        "I have shared the news.",
        "J'ai partagé la nouvelle.",
        "Zij hebben de kosten gedeeld.",
        "They have shared the costs.",
        "Elles ont partagé les coûts.",
        "Wij deelden de taart.",
        "We shared the cake.",
        "Nous avons partagé le gâteau.",
        "Zij deelden de winst.",
        "They divided the profit.",
        "Elles ont partagé le profit.",
    ),
    (
        "opslaan",
        "to save (file)",
        "enregistrer",
        "heeft/hebben opgeslagen",
        "sloeg op · sloegen op",
        "Ik heb het document opgeslagen.",
        "I have saved the document.",
        "J'ai enregistré le document.",
        "Zij hebben de wijzigingen opgeslagen.",
        "They have saved the changes.",
        "Elles ont enregistré les modifications.",
        "Hij sloeg het bestand op.",
        "He saved the file.",
        "Il a enregistré le fichier.",
        "Zij sloegen alles op in de cloud.",
        "They saved everything to the cloud.",
        "Elles ont tout enregistré dans le cloud.",
    ),
    (
        "verwijderen",
        "to remove",
        "supprimer",
        "heeft/hebben verwijderd",
        "verwijderde · verwijderden",
        "Ik heb het virus verwijderd.",
        "I have removed the virus.",
        "J'ai supprimé le virus.",
        "Zij hebben de oude bestanden verwijderd.",
        "They have removed the old files.",
        "Elles ont supprimé les anciens fichiers.",
        "Hij verwijderde de sticker.",
        "He removed the sticker.",
        "Il a enlevé l'autocollant.",
        "Zij verwijderden spam.",
        "They removed spam.",
        "Elles ont supprimé le spam.",
    ),
    (
        "installeren",
        "to install",
        "installer",
        "heeft/hebben geïnstalleerd",
        "installeerde · installeerden",
        "Ik heb de software geïnstalleerd.",
        "I have installed the software.",
        "J'ai installé le logiciel.",
        "Zij hebben zonnepanelen geïnstalleerd.",
        "They have installed solar panels.",
        "Elles ont installé des panneaux solaires.",
        "Hij installeerde de printer.",
        "He installed the printer.",
        "Il a installé l'imprimante.",
        "Zij installeerden de app.",
        "They installed the app.",
        "Elles ont installé l'appli.",
    ),
    (
        "updaten",
        "to update",
        "mettre à jour",
        "heeft/hebben geüpdatet",
        "updatete · updateten",
        "Ik heb het systeem geüpdatet.",
        "I have updated the system.",
        "J'ai mis à jour le système.",
        "Zij hebben de app geüpdatet.",
        "They have updated the app.",
        "Elles ont mis à jour l'appli.",
        "Hij updatete het profiel.",
        "He updated the profile.",
        "Il a mis à jour le profil.",
        "Zij updateten de lijst.",
        "They updated the list.",
        "Elles ont mis à jour la liste.",
    ),
    (
        "synchroniseren",
        "to synchronise",
        "synchroniser",
        "heeft/hebben gesynchroniseerd",
        "synchroniseerde · synchroniseerden",
        "Ik heb de agenda gesynchroniseerd.",
        "I have synced the calendar.",
        "J'ai synchronisé l'agenda.",
        "Zij hebben de apparaten gesynchroniseerd.",
        "They have synced the devices.",
        "Elles ont synchronisé les appareils.",
        "Hij synchroniseerde de data.",
        "He synced the data.",
        "Il a synchronisé les données.",
        "Zij synchroniseerden alles.",
        "They synced everything.",
        "Elles ont tout synchronisé.",
    ),
    (
        "reserveren",
        "to book / reserve",
        "réserver",
        "heeft/hebben gereserveerd",
        "reserveerde · reserveerden",
        "Ik heb een tafel gereserveerd.",
        "I have reserved a table.",
        "J'ai réservé une table.",
        "Zij hebben tickets gereserveerd.",
        "They have reserved tickets.",
        "Elles ont réservé des billets.",
        "Hij reserveerde een hotel.",
        "He booked a hotel.",
        "Il a réservé un hôtel.",
        "Zij reserveerden online.",
        "They booked online.",
        "Elles ont réservé en ligne.",
    ),
    (
        "annuleren",
        "to cancel",
        "annuler",
        "heeft/hebben geannuleerd",
        "annuleerde · annuleerden",
        "Ik heb de vlucht geannuleerd.",
        "I have cancelled the flight.",
        "J'ai annulé le vol.",
        "Zij hebben het abonnement geannuleerd.",
        "They have cancelled the subscription.",
        "Elles ont annulé l'abonnement.",
        "Hij annuleerde de afspraak.",
        "He cancelled the appointment.",
        "Il a annulé le rendez-vous.",
        "Zij annuleerden de bestelling.",
        "They cancelled the order.",
        "Elles ont annulé la commande.",
    ),
    (
        "bevestigen",
        "to confirm",
        "confirmer",
        "heeft/hebben bevestigd",
        "bevestigde · bevestigden",
        "Ik heb de reservering bevestigd.",
        "I have confirmed the reservation.",
        "J'ai confirmé la réservation.",
        "Zij hebben het adres bevestigd.",
        "They have confirmed the address.",
        "Elles ont confirmé l'adresse.",
        "Hij bevestigde het gerucht.",
        "He confirmed the rumour.",
        "Il a confirmé la rumeur.",
        "Zij bevestigden de datum.",
        "They confirmed the date.",
        "Elles ont confirmé la date.",
    ),
    (
        "afwijzen",
        "to reject",
        "rejeter",
        "heeft/hebben afgewezen",
        "wees af · wezen af",
        "Ik heb het voorstel afgewezen.",
        "I have rejected the proposal.",
        "J'ai rejeté la proposition.",
        "Zij hebben de aanvraag afgewezen.",
        "They have rejected the application.",
        "Elles ont rejeté la demande.",
        "Hij wees de claim af.",
        "He rejected the claim.",
        "Il a rejeté la réclamation.",
        "Zij wezen het idee af.",
        "They rejected the idea.",
        "Elles ont rejeté l'idée.",
    ),
    (
        "exporteren",
        "to export",
        "exporter",
        "heeft/hebben geëxporteerd",
        "exporteerde · exporteerden",
        "Wij hebben data geëxporteerd.",
        "We have exported data.",
        "Nous avons exporté des données.",
        "Zij hebben naar CSV geëxporteerd.",
        "They have exported to CSV.",
        "Elles ont exporté vers CSV.",
        "Hij exporteerde de lijst.",
        "He exported the list.",
        "Il a exporté la liste.",
        "Zij exporteerden rapporten.",
        "They exported reports.",
        "Elles ont exporté des rapports.",
    ),
    (
        "importeren",
        "to import",
        "importer",
        "heeft/hebben geïmporteerd",
        "importeerde · importeerden",
        "Zij hebben grondstoffen geïmporteerd.",
        "They have imported raw materials.",
        "Elles ont importé des matières premières.",
        "Wij hebben de database geïmporteerd.",
        "We have imported the database.",
        "Nous avons importé la base de données.",
        "Hij importeerde wijn.",
        "He imported wine.",
        "Il a importé du vin.",
        "Zij importeerden machines.",
        "They imported machines.",
        "Elles ont importé des machines.",
    ),
    (
        "inloggen",
        "to log in",
        "se connecter",
        "is/zijn ingelogd",
        "logde in · logden in",
        "Ik ben ingelogd op de site.",
        "I have logged in to the site.",
        "Je me suis connecté au site.",
        "Zij zijn op hun account ingelogd.",
        "They have logged into their account.",
        "Elles se sont connectées à leur compte.",
        "Hij logde in met een wachtwoord.",
        "He logged in with a password.",
        "Il s'est connecté avec un mot de passe.",
        "Zij logden in via de app.",
        "They logged in via the app.",
        "Elles se sont connectées via l'appli.",
    ),
    (
        "uitloggen",
        "to log out",
        "se déconnecter",
        "is/zijn uitgelogd",
        "logde uit · logden uit",
        "Ik ben veilig uitgelogd.",
        "I have logged out safely.",
        "Je me suis déconnecté en toute sécurité.",
        "Zij zijn overal uitgelogd.",
        "They have logged out everywhere.",
        "Elles se sont déconnectées partout.",
        "Hij logde uit op het werk.",
        "He logged out at work.",
        "Il s'est déconnecté au travail.",
        "Zij logden uit na gebruik.",
        "They logged out after use.",
        "Elles se sont déconnectées après utilisation.",
    ),
    (
        "inzien",
        "to review / peruse",
        "consulter",
        "heeft/hebben ingezien",
        "inzag · inzagen",
        "Ik heb het contract ingezien.",
        "I have reviewed the contract.",
        "J'ai consulté le contrat.",
        "Zij hebben de fout ingezien.",
        "They have recognized their mistake.",
        "Elles ont reconnu leur erreur.",
        "Hij inzag de risico's.",
        "He saw the risks.",
        "Il a vu les risques.",
        "Zij inzagen het probleem.",
        "They recognised the problem.",
        "Elles ont reconnu le problème.",
    ),
    (
        "meewerken",
        "to cooperate",
        "collaborer",
        "heeft/hebben meegewerkt",
        "werkte mee · werkten mee",
        "Ik heb aan het project meegewerkt.",
        "I have cooperated on the project.",
        "J'ai collaboré au projet.",
        "Zij hebben goed meegewerkt.",
        "They have cooperated well.",
        "Elles ont bien collaboré.",
        "Hij werkte mee aan het onderzoek.",
        "He cooperated with the research.",
        "Il a collaboré à l'enquête.",
        "Zij werkten mee aan de enquête.",
        "They cooperated with the survey.",
        "Elles ont collaboré à l'enquête.",
    ),
    (
        "meehelpen",
        "to help along",
        "aider",
        "heeft/hebben meegeholpen",
        "hielp mee · hielpen mee",
        "Ik heb in de keuken meegeholpen.",
        "I have helped in the kitchen.",
        "J'ai aidé dans la cuisine.",
        "Zij hebben bij de verhuizing meegeholpen.",
        "They have helped with the move.",
        "Elles ont aidé pour le déménagement.",
        "Hij hielp mee met opruimen.",
        "He helped tidy up.",
        "Il a aidé à ranger.",
        "Zij hielpen mee op het feest.",
        "They helped at the party.",
        "Elles ont aidé à la fête.",
    ),
    (
        "vervangen",
        "to replace",
        "remplacer",
        "heeft/hebben vervangen",
        "verving · vervingen",
        "Ik heb de batterij vervangen.",
        "I have replaced the battery.",
        "J'ai remplacé la pile.",
        "Zij hebben het onderdeel vervangen.",
        "They have replaced the part.",
        "Elles ont remplacé la pièce.",
        "Hij verving de lamp.",
        "He replaced the lamp.",
        "Il a remplacé l'ampoule.",
        "Zij vervingen het personeel.",
        "They replaced the staff.",
        "Elles ont remplacé le personnel.",
    ),
]
