# Perfectum (VTT) example sentences — cards 1–50 (lemmas must match index.html).
VTT_MANUAL = {
    "zijn": (
        "Ik ben blij geweest.",
        "I have been happy.",
        "J'ai été content.",
        "Wij zijn er samen geweest.",
        "We have been there together.",
        "Nous y avons été ensemble.",
    ),
    "hebben": (
        "Ik heb vandaag tijd gehad.",
        "I have had time today.",
        "J'ai eu du temps aujourd'hui.",
        "Zij hebben veel vragen gehad.",
        "They have had many questions.",
        "Elles ont eu beaucoup de questions.",
    ),
    "worden": (
        "Ik ben een winkelbediende geworden.",
        "I have become a shop assistant.",
        "Je suis devenu vendeur.",
        "Wij zijn goede vrienden geworden.",
        "We have become good friends.",
        "Nous sommes devenus de bons amis.",
    ),
    "gaan": (
        "Ik ben naar huis gegaan.",
        "I have gone home.",
        "Je suis rentré chez moi.",
        "Zij zijn met de bus gegaan.",
        "They have gone by bus.",
        "Elles sont allées en bus.",
    ),
    "komen": (
        "Ik ben te laat gekomen.",
        "I have arrived too late.",
        "Je suis arrivé trop tard.",
        "Wij zijn uit Berlijn gekomen.",
        "We have come from Berlin.",
        "Nous sommes venus de Berlin.",
    ),
    "blijven": (
        "Ik ben thuis gebleven.",
        "I have stayed home.",
        "Je suis resté chez moi.",
        "Zij zijn een week langer gebleven.",
        "They have stayed a week longer.",
        "Elles sont restées une semaine de plus.",
    ),
    "zitten": (
        "Ik heb uren gezeten.",
        "I have sat for hours.",
        "Je suis resté assis des heures.",
        "Zij hebben in de zaal gezeten.",
        "They have sat in the hall.",
        "Elles se sont assises dans la salle.",
    ),
    "staan": (
        "Ik heb lang in de rij gestaan.",
        "I have stood in line for a long time.",
        "J'ai longtemps fait la queue.",
        "Wij hebben op het perron gestaan.",
        "We have stood on the platform.",
        "Nous nous sommes tenus sur le quai.",
    ),
    "liggen": (
        "Het boek heeft op tafel gelegen.",
        "The book has lain on the table.",
        "Le livre est resté sur la table.",
        "De sleutels hebben in de la gelegen.",
        "The keys have lain in the drawer.",
        "Les clés sont restées dans le tiroir.",
    ),
    "lopen": (
        "Ik ben ver gelopen.",
        "I have walked a long way.",
        "J'ai été loin à pied.",
        "Zij zijn door het park gelopen.",
        "They have walked through the park.",
        "Elles ont traversé le parc à pied.",
    ),
    "doen": (
        "Ik heb mijn best gedaan.",
        "I have done my best.",
        "J'ai fait de mon mieux.",
        "Wij hebben het samen gedaan.",
        "We have done it together.",
        "Nous l'avons fait ensemble.",
    ),
    "maken": (
        "Zij heeft soep gemaakt.",
        "She has made soup.",
        "Elle a fait de la soupe.",
        "Zij hebben veel lawaai gemaakt.",
        "They have made a lot of noise.",
        "Elles ont fait beaucoup de bruit.",
    ),
    "zeggen": (
        "Hij heeft de waarheid gezegd.",
        "He has told the truth.",
        "Il a dit la vérité.",
        "Wij hebben het nog een keer gezegd.",
        "We have said it again.",
        "Nous l'avons répété.",
    ),
    "geven": (
        "Ik heb haar een cadeau gegeven.",
        "I have given her a present.",
        "Je lui ai offert un cadeau.",
        "Wij hebben aan het goede doel gegeven.",
        "We have given to charity.",
        "Nous avons donné à une association.",
    ),
    "nemen": (
        "Jij hebt de verkeerde afslag genomen.",
        "You have taken the wrong exit.",
        "Tu as pris la mauvaise sortie.",
        "Wij hebben een taxi genomen.",
        "We have taken a taxi.",
        "Nous avons pris un taxi.",
    ),
    "zien": (
        "Ik heb een regenboog gezien.",
        "I have seen a rainbow.",
        "J'ai vu un arc-en-ciel.",
        "Zij hebben de film al gezien.",
        "They have already seen the film.",
        "Elles ont déjà vu le film.",
    ),
    "weten": (
        "Ik heb het altijd geweten.",
        "I have always known it.",
        "Je l'ai toujours su.",
        "Wij hebben niet geweten waar we moesten zijn.",
        "We have not known where we had to be.",
        "Nous n'avons pas su où aller.",
    ),
    "vinden": (
        "Ik heb mijn sleutel gevonden.",
        "I have found my key.",
        "J'ai retrouvé ma clé.",
        "Zij hebben geen plek gevonden.",
        "They have found no spot.",
        "Elles n'ont trouvé aucune place.",
    ),
    "denken": (
        "Ik heb aan jou gedacht.",
        "I have thought of you.",
        "J'ai pensé à toi.",
        "Wij hebben aan een oplossing gedacht.",
        "We have thought of a solution.",
        "Nous avons pensé à une solution.",
    ),
    "laten": (
        "Ik heb het mee laten maken.",
        "I have had it made.",
        "Je l'ai fait faire.",
        "Wij hebben ons niet laten zien.",
        "We have not let ourselves be seen.",
        "Nous ne nous sommes pas montrés.",
    ),
    "willen": (
        "Ik heb altijd willen leren.",
        "I have always wanted to learn.",
        "J'ai toujours voulu apprendre.",
        "Wij hebben niet willen wachten.",
        "We have not wanted to wait.",
        "Nous n'avons pas voulu attendre.",
    ),
    "moeten": (
        "Ik heb moeten wachten.",
        "I have had to wait.",
        "J'ai dû attendre.",
        "Zij hebben vroeg moeten vertrekken.",
        "They have had to leave early.",
        "Elles ont dû partir tôt.",
    ),
    "kunnen": (
        "Ik heb het niet gekund.",
        "I have not been able to do it.",
        "Je n'ai pas pu le faire.",
        "Zij hebben niet kunnen komen.",
        "They have not been able to come.",
        "Elles n'ont pas pu venir.",
    ),
    "mogen": (
        "Ik heb niet mogen gaan.",
        "I have not been allowed to go.",
        "Je n'ai pas eu le droit d'y aller.",
        "Wij hebben niet mogen roken.",
        "We have not been allowed to smoke.",
        "Nous n'avons pas eu le droit de fumer.",
    ),
    "brengen": (
        "Ik heb de kinderen gebracht.",
        "I have brought the children.",
        "J'ai amené les enfants.",
        "Zij hebben de boodschappen gebracht.",
        "They have brought the groceries.",
        "Elles ont apporté les courses.",
    ),
    "halen": (
        "Ik heb mijn pakje gehaald.",
        "I have picked up my parcel.",
        "J'ai récupéré mon colis.",
        "Wij hebben water gehaald.",
        "We have fetched water.",
        "Nous avons pris de l'eau.",
    ),
    "houden": (
        "Ik heb van haar gehouden.",
        "I have loved her.",
        "Je l'ai aimée.",
        "Wij hebben het huis warm gehouden.",
        "We have kept the house warm.",
        "Nous avons gardé la maison au chaud.",
    ),
    "kopen": (
        "Ik heb brood gekocht.",
        "I have bought bread.",
        "J'ai acheté du pain.",
        "Zij hebben een huis gekocht.",
        "They have bought a house.",
        "Elles ont acheté une maison.",
    ),
    "verkopen": (
        "Ik heb mijn auto verkocht.",
        "I have sold my car.",
        "J'ai vendu ma voiture.",
        "Zij hebben veel boeken verkocht.",
        "They have sold many books.",
        "Elles ont vendu beaucoup de livres.",
    ),
    "betalen": (
        "Ik heb contant betaald.",
        "I have paid in cash.",
        "J'ai payé en espèces.",
        "Wij hebben de rekening betaald.",
        "We have paid the bill.",
        "Nous avons payé l'addition.",
    ),
    "werken": (
        "Ik heb de hele dag gewerkt.",
        "I have worked all day.",
        "J'ai travaillé toute la journée.",
        "Zij hebben samen gewerkt.",
        "They have worked together.",
        "Elles ont travaillé ensemble.",
    ),
    "spelen": (
        "Ik heb schaak gespeeld.",
        "I have played chess.",
        "J'ai joué aux échecs.",
        "Zij hebben in de zaal gespeeld.",
        "They have played in the hall.",
        "Elles ont joué dans la salle.",
    ),
    "leren": (
        "Ik heb Nederlands geleerd.",
        "I have learned Dutch.",
        "J'ai appris le néerlandais.",
        "Wij hebben veel geleerd.",
        "We have learned a lot.",
        "Nous avons beaucoup appris.",
    ),
    "studeren": (
        "Ik heb geneeskunde gestudeerd.",
        "I have studied medicine.",
        "J'ai étudié la médecine.",
        "Zij hebben in Leiden gestudeerd.",
        "They have studied in Leiden.",
        "Elles ont étudié à Leyde.",
    ),
    "wonen": (
        "Ik heb in Amsterdam gewoond.",
        "I have lived in Amsterdam.",
        "J'ai vécu à Amsterdam.",
        "Wij hebben jaren in de stad gewoond.",
        "We have lived in the city for years.",
        "Nous avons vécu des années en ville.",
    ),
    "lezen": (
        "Ik heb het boek gelezen.",
        "I have read the book.",
        "J'ai lu le livre.",
        "Zij hebben de krant gelezen.",
        "They have read the newspaper.",
        "Elles ont lu le journal.",
    ),
    "schrijven": (
        "Ik heb een brief geschreven.",
        "I have written a letter.",
        "J'ai écrit une lettre.",
        "Wij hebben een rapport geschreven.",
        "We have written a report.",
        "Nous avons écrit un rapport.",
    ),
    "spreken": (
        "Ik heb met haar gesproken.",
        "I have spoken with her.",
        "Je lui ai parlé.",
        "Zij hebben Engels gesproken.",
        "They have spoken English.",
        "Elles ont parlé anglais.",
    ),
    "luisteren": (
        "Ik heb naar de radio geluisterd.",
        "I have listened to the radio.",
        "J'ai écouté la radio.",
        "Wij hebben naar muziek geluisterd.",
        "We have listened to music.",
        "Nous avons écouté de la musique.",
    ),
    "praten": (
        "Ik heb met haar gepraat.",
        "I have chatted with her.",
        "J'ai discuté avec elle.",
        "Zij hebben lang gepraat.",
        "They have talked for a long time.",
        "Elles ont longtemps parlé.",
    ),
    "bellen": (
        "Ik heb naar huis gebeld.",
        "I have called home.",
        "J'ai téléphoné à la maison.",
        "Wij hebben de dokter gebeld.",
        "We have called the doctor.",
        "Nous avons appelé le médecin.",
    ),
    "zoeken": (
        "Ik heb mijn telefoon gezocht.",
        "I have looked for my phone.",
        "J'ai cherché mon téléphone.",
        "Zij hebben hulp gezocht.",
        "They have looked for help.",
        "Elles ont cherché de l'aide.",
    ),
    "krijgen": (
        "Ik heb een cadeau gekregen.",
        "I have received a present.",
        "J'ai reçu un cadeau.",
        "Zij hebben goed nieuws gekregen.",
        "They have received good news.",
        "Elles ont reçu une bonne nouvelle.",
    ),
    "gebruiken": (
        "Ik heb een pen gebruikt.",
        "I have used a pen.",
        "J'ai utilisé un stylo.",
        "Zij hebben het gereedschap gebruikt.",
        "They have used the tools.",
        "Elles ont utilisé les outils.",
    ),
    "proberen": (
        "Ik heb het geprobeerd.",
        "I have tried it.",
        "J'ai essayé.",
        "Wij hebben het opnieuw geprobeerd.",
        "We have tried again.",
        "Nous avons réessayé.",
    ),
    "hopen": (
        "Ik heb gehoopt op goed weer.",
        "I have hoped for good weather.",
        "J'ai espéré beau temps.",
        "Zij hebben op beter gehoopt.",
        "They have hoped for better.",
        "Elles ont espéré mieux.",
    ),
    "geloven": (
        "Ik heb het geloofd.",
        "I have believed it.",
        "Je l'ai cru.",
        "Wij hebben haar verhaal geloofd.",
        "We have believed her story.",
        "Nous avons cru son histoire.",
    ),
    "begrijpen": (
        "Ik heb het begrepen.",
        "I have understood it.",
        "Je l'ai compris.",
        "Zij hebben de uitleg begrepen.",
        "They have understood the explanation.",
        "Elles ont compris l'explication.",
    ),
    "vergeten": (
        "Ik heb mijn paraplu vergeten.",
        "I have forgotten my umbrella.",
        "J'ai oublié mon parapluie.",
        "Zij hebben de afspraak vergeten.",
        "They have forgotten the appointment.",
        "Elles ont oublié le rendez-vous.",
    ),
    "beginnen": (
        "Ik ben op tijd begonnen.",
        "I have started on time.",
        "J'ai commencé à l'heure.",
        "Wij zijn samen begonnen.",
        "We have started together.",
        "Nous avons commencé ensemble.",
    ),
}
