# Perfectum (VTT) example sentences — cards 51–100.
VTT_MANUAL = {
    "eten": (
        "Ik heb pasta gegeten.",
        "I have eaten pasta.",
        "J'ai mangé des pâtes.",
        "Zij hebben samen gegeten.",
        "They have eaten together.",
        "Elles ont mangé ensemble.",
    ),
    "drinken": (
        "Ik heb water gedronken.",
        "I have drunk water.",
        "J'ai bu de l'eau.",
        "Wij hebben koffie gedronken.",
        "We have drunk coffee.",
        "Nous avons bu du café.",
    ),
    "slapen": (
        "Ik heb goed geslapen.",
        "I have slept well.",
        "J'ai bien dormi.",
        "Zij hebben in de trein geslapen.",
        "They have slept on the train.",
        "Elles ont dormi dans le train.",
    ),
    "koken": (
        "Ik heb risotto gekookt.",
        "I have cooked risotto.",
        "J'ai cuisiné un risotto.",
        "Wij hebben samen gekookt.",
        "We have cooked together.",
        "Nous avons cuisiné ensemble.",
    ),
    "helpen": (
        "Ik heb haar geholpen.",
        "I have helped her.",
        "Je l'ai aidée.",
        "Zij hebben bij de verhuizing geholpen.",
        "They have helped with the move.",
        "Elles ont aidé au déménagement.",
    ),
    "vragen": (
        "Ik heb om hulp gevraagd.",
        "I have asked for help.",
        "J'ai demandé de l'aide.",
        "Zij hebben naar de prijs gevraagd.",
        "They have asked for the price.",
        "Elles ont demandé le prix.",
    ),
    "antwoorden": (
        "Ik heb op de mail geantwoord.",
        "I have replied to the email.",
        "J'ai répondu au mail.",
        "Wij hebben niet geantwoord.",
        "We have not answered.",
        "Nous n'avons pas répondu.",
    ),
    "vertellen": (
        "Ik heb een verhaal verteld.",
        "I have told a story.",
        "J'ai raconté une histoire.",
        "Zij hebben de waarheid verteld.",
        "They have told the truth.",
        "Elles ont raconté la vérité.",
    ),
    "horen": (
        "Ik heb het nieuws gehoord.",
        "I have heard the news.",
        "J'ai entendu les nouvelles.",
        "Wij hebben muziek gehoord.",
        "We have heard music.",
        "Nous avons entendu de la musique.",
    ),
    "noemen": (
        "Ik heb hem zo genoemd.",
        "I have called him that.",
        "Je l'ai appelé ainsi.",
        "Zij hebben het anders genoemd.",
        "They have called it something else.",
        "Elles l'ont nommé autrement.",
    ),
    "kiezen": (
        "Ik heb voor jou gekozen.",
        "I have chosen you.",
        "Je t'ai choisi.",
        "Zij hebben een andere route gekozen.",
        "They have chosen another route.",
        "Elles ont choisi un autre itinéraire.",
    ),
    "verliezen": (
        "Ik heb mijn sleutel verloren.",
        "I have lost my key.",
        "J'ai perdu ma clé.",
        "Zij hebben de wedstrijd verloren.",
        "They have lost the match.",
        "Elles ont perdu le match.",
    ),
    "winnen": (
        "Ik heb een prijs gewonnen.",
        "I have won a prize.",
        "J'ai gagné un prix.",
        "Wij hebben samen gewonnen.",
        "We have won together.",
        "Nous avons gagné ensemble.",
    ),
    "trekken": (
        "Ik heb de deur dichtgetrokken.",
        "I have pulled the door shut.",
        "J'ai tiré la porte.",
        "Zij hebben aan de bel getrokken.",
        "They have pulled the bell.",
        "Elles ont tiré la sonnette.",
    ),
    "dragen": (
        "Ik heb de tas gedragen.",
        "I have carried the bag.",
        "J'ai porté le sac.",
        "Zij hebben de last gedragen.",
        "They have borne the burden.",
        "Elles ont porté le fardeau.",
    ),
    "breken": (
        "Ik heb mijn been gebroken.",
        "I have broken my leg.",
        "Je me suis cassé une jambe.",
        "Zij hebben het glas gebroken.",
        "They have broken the glass.",
        "Elles ont cassé le verre.",
    ),
    "snijden": (
        "Ik heb brood gesneden.",
        "I have cut bread.",
        "J'ai coupé du pain.",
        "Zij hebben de groente gesneden.",
        "They have cut the vegetables.",
        "Elles ont coupé les légumes.",
    ),
    "vliegen": (
        "Ik ben naar Parijs gevlogen.",
        "I have flown to Paris.",
        "Je suis allé à Paris en avion.",
        "Zij zijn naar Rome gevlogen.",
        "They have flown to Rome.",
        "Elles ont volé vers Rome.",
    ),
    "zwemmen": (
        "Ik heb in zee gezwommen.",
        "I have swum in the sea.",
        "J'ai nagé dans la mer.",
        "Zij hebben in het zwembad gezwommen.",
        "They have swum in the pool.",
        "Elles ont nagé dans la piscine.",
    ),
    "rijden": (
        "Ik ben naar het werk gereden.",
        "I have driven to work.",
        "Je suis allé au travail en voiture.",
        "Wij hebben uren door de sneeuw gereden.",
        "We have driven for hours through the snow.",
        "Nous avons roulé des heures dans la neige.",
    ),
    "fietsen": (
        "Ik ben naar school gefietst.",
        "I have cycled to school.",
        "Je suis allé à l'école à vélo.",
        "Zij zijn mee gefietst.",
        "They have cycled along.",
        "Elles sont venues à vélo.",
    ),
    "reizen": (
        "Ik heb door Europa gereisd.",
        "I have travelled through Europe.",
        "J'ai voyagé en Europe.",
        "Wij hebben veel gereisd.",
        "We have travelled a lot.",
        "Nous avons beaucoup voyagé.",
    ),
    "bezoeken": (
        "Ik heb mijn oma bezocht.",
        "I have visited my grandmother.",
        "J'ai rendu visite à ma grand-mère.",
        "Zij hebben het museum bezocht.",
        "They have visited the museum.",
        "Elles ont visité le musée.",
    ),
    "ontmoeten": (
        "Ik heb een oude vriend ontmoet.",
        "I have met an old friend.",
        "J'ai rencontré un vieil ami.",
        "Wij hebben elkaar ontmoet.",
        "We have met each other.",
        "Nous nous sommes rencontrés.",
    ),
    "bedanken": (
        "Ik heb haar bedankt.",
        "I have thanked her.",
        "Je l'ai remerciée.",
        "Wij hebben iedereen bedankt.",
        "We have thanked everyone.",
        "Nous avons remercié tout le monde.",
    ),
    "passen": (
        "Het heeft niet gepast.",
        "It has not fitted.",
        "Ça n'allait pas.",
        "De schoenen hebben gepast.",
        "The shoes have fitted.",
        "Les chaussures allaient bien.",
    ),
    "missen": (
        "Ik heb de trein gemist.",
        "I have missed the train.",
        "J'ai raté le train.",
        "Zij hebben de kans gemist.",
        "They have missed the chance.",
        "Elles ont raté l'occasion.",
    ),
    "wachten": (
        "Ik heb een uur gewacht.",
        "I have waited an hour.",
        "J'ai attendu une heure.",
        "Zij hebben op ons gewacht.",
        "They have waited for us.",
        "Elles nous ont attendus.",
    ),
    "lijken": (
        "Het heeft op regen geleken.",
        "It has looked like rain.",
        "On aurait dit de la pluie.",
        "Zij hebben op elkaar geleken.",
        "They have looked alike.",
        "Elles se sont ressemblées.",
    ),
    "voelen": (
        "Ik heb me beter gevoeld.",
        "I have felt better.",
        "Je me suis senti mieux.",
        "Zij hebben zich ziek gevoeld.",
        "They have felt ill.",
        "Elles se sont senties malades.",
    ),
    "leven": (
        "Ik heb lang geleefd.",
        "I have lived a long time.",
        "J'ai vécu longtemps.",
        "Zij hebben in vrede geleefd.",
        "They have lived in peace.",
        "Elles ont vécu en paix.",
    ),
    "sterven": (
        "Hij is vroeg gestorven.",
        "He has died young.",
        "Il est mort jeune.",
        "Zij zijn in het ziekenhuis gestorven.",
        "They have died in hospital.",
        "Elles sont mortes à l'hôpital.",
    ),
    "trouwen": (
        "Ik ben getrouwd.",
        "I have got married.",
        "Je me suis marié.",
        "Zij zijn in de zomer getrouwd.",
        "They have married in summer.",
        "Elles se sont mariées en été.",
    ),
    "lachen": (
        "Ik heb hard gelachen.",
        "I have laughed hard.",
        "J'ai beaucoup ri.",
        "Zij hebben om het grapje gelachen.",
        "They have laughed at the joke.",
        "Elles ont ri de la blague.",
    ),
    "dansen": (
        "Ik heb de hele avond gedanst.",
        "I have danced all evening.",
        "J'ai dansé toute la soirée.",
        "Zij hebben samen gedanst.",
        "They have danced together.",
        "Elles ont dansé ensemble.",
    ),
    "zingen": (
        "Ik heb een lied gezongen.",
        "I have sung a song.",
        "J'ai chanté une chanson.",
        "Zij hebben in het koor gezongen.",
        "They have sung in the choir.",
        "Elles ont chanté dans le chœur.",
    ),
    "springen": (
        "Ik ben hoog gesprongen.",
        "I have jumped high.",
        "J'ai sauté haut.",
        "Zij zijn in het water gesprongen.",
        "They have jumped into the water.",
        "Elles ont sauté dans l'eau.",
    ),
    "vallen": (
        "Ik ben op het ijs gevallen.",
        "I have fallen on the ice.",
        "Je suis tombé sur la glace.",
        "Zij zijn bijna gevallen.",
        "They have almost fallen.",
        "Elles ont failli tomber.",
    ),
    "opstaan": (
        "Ik ben vroeg opgestaan.",
        "I have got up early.",
        "Je me suis levé tôt.",
        "Zij zijn laat opgestaan.",
        "They have got up late.",
        "Elles se sont levées tard.",
    ),
    "aankomen": (
        "De trein is te laat aangekomen.",
        "The train has arrived too late.",
        "Le train est arrivé en retard.",
        "Zij zijn veilig aangekomen.",
        "They have arrived safely.",
        "Elles sont arrivées sans encombre.",
    ),
    "weggaan": (
        "Hij is stilletjes weggegaan.",
        "He has left quietly.",
        "Il est parti discrètement.",
        "Zij zijn zonder afscheid weggegaan.",
        "They have left without saying goodbye.",
        "Elles sont parties sans dire au revoir.",
    ),
    "meenemen": (
        "Ik heb mijn laptop meegenomen.",
        "I have taken my laptop along.",
        "J'ai pris mon ordinateur portable.",
        "Zij hebben snacks meegenomen.",
        "They have brought snacks along.",
        "Elles ont apporté des snacks.",
    ),
    "verstaan": (
        "Ik heb hem niet verstaan.",
        "I have not understood him (speech).",
        "Je ne l'ai pas compris.",
        "Zij hebben elkaar niet verstaan.",
        "They have not understood each other.",
        "Elles ne se sont pas comprises.",
    ),
    "herinneren": (
        "Ik heb me dat herinnerd.",
        "I have remembered that.",
        "Je me suis rappelé cela.",
        "Zij hebben zich alles herinnerd.",
        "They have remembered everything.",
        "Elles se sont tout rappelé.",
    ),
    "oefenen": (
        "Ik heb elke dag geoefend.",
        "I have practised every day.",
        "Je me suis entraîné chaque jour.",
        "Zij hebben voor het concert geoefend.",
        "They have practised for the concert.",
        "Elles ont répété pour le concert.",
    ),
    "dromen": (
        "Ik heb van vakantie gedroomd.",
        "I have dreamed of holiday.",
        "J'ai rêvé de vacances.",
        "Zij hebben van succes gedroomd.",
        "They have dreamed of success.",
        "Elles ont rêvé de réussir.",
    ),
    "bestellen": (
        "Ik heb koffie besteld.",
        "I have ordered coffee.",
        "J'ai commandé un café.",
        "Zij hebben drie pizza's besteld.",
        "They have ordered three pizzas.",
        "Elles ont commandé trois pizzas.",
    ),
    "bereiken": (
        "Hij heeft het doel bereikt.",
        "He has reached the goal.",
        "Il a atteint son objectif.",
        "Zij hebben de top bereikt.",
        "They have reached the top.",
        "Elles ont atteint le sommet.",
    ),
    "beslissen": (
        "Zij heeft alleen beslist.",
        "She has decided alone.",
        "Elle a décidé seule.",
        "Zij hebben samen beslist.",
        "They have decided together.",
        "Elles ont décidé ensemble.",
    ),
    "bouwen": (
        "Wij hebben een schuur gebouwd.",
        "We have built a shed.",
        "Nous avons construit une remise.",
        "Zij hebben een nieuw huis gebouwd.",
        "They have built a new house.",
        "Elles ont construit une nouvelle maison.",
    ),
}
